open-telemetry/opentelemetry-js-contrib

plugins/node/opentelemetry-plugin-pg/package.json
plugins/node/opentelemetry-plugin-pg/src/pg.ts

- Fixes #24 
- Adds `8.*` to versions matrix. Only test on `pg@8.*`

chore: bump to pg8.*

---

CHANGELOG.md
package.json

Release proposal https://github.com/open-telemetry/opentelemetry-js-contrib/releases/tag/untagged-cff4bed803689ea5e09a

chore: gRPC census binary propagator release

---

.circleci/config.yml

-remove node 13 tests
-removed node 13 tests from config.yml

remove node 13 tests

---

plugins/node/opentelemetry-plugin-express/src/express.ts

fix(express): avoid unref since not available in node 8 #78

---

plugins/node/opentelemetry-plugin-redis/package.json
plugins/node/opentelemetry-plugin-redis/test/redis.test.ts

chore(deps): update dependency @types/redis to v2.8.24

---

propagators/README.md

add license url

---

plugins/node/opentelemetry-plugin-dns/package.json
plugins/node/opentelemetry-plugin-express/package.json
plugins/node/opentelemetry-plugin-ioredis/package.json
plugins/node/opentelemetry-plugin-mongodb/package.json
plugins/node/opentelemetry-plugin-mysql/package.json
plugins/node/opentelemetry-plugin-pg-pool/package.json
plugins/node/opentelemetry-plugin-pg/package.json
plugins/node/opentelemetry-plugin-redis/package.json
plugins/web/opentelemetry-plugin-document-load/package.json
plugins/web/opentelemetry-plugin-user-interaction/package.json
propagators/opentelemetry-propagator-grpc-census-binary/package.json
propagators/opentelemetry-propagator-jaeger/package.json

chore: bump codecov

---

.github/workflows/lint.yml

- Fixing caching issue for the lint action
- Caching packages in the contrib repo

fix: fixing caching issue for lint action

---

README.md

- n/a
- follow up to https://github.com/open-telemetry/opentelemetry-js/pull/1543 to mention dns enablement and add hapi+koa links

docs: update dns status and add hapi koa

---

packages/opentelemetry-host-metrics/README.md

Fixing links in host metrics readme

feat: fixing links in host metrics readme

---

examples/graphql/tracer.js
plugins/node/opentelemetry-instrumentation-graphql/src/graphql.ts
plugins/node/opentelemetry-instrumentation-graphql/src/types.ts
plugins/node/opentelemetry-instrumentation-graphql/src/utils.ts

- Fixes #360 - supporting version 14+
- Fixing the graphql example to latest version

chore: fixing the graphql example and allowing support version of graph from ver 14

---

plugins/node/opentelemetry-instrumentation-mongodb/src/mongodb.ts

Sadly i wasn't able to find a case which reprocuce the reported error, the original code was wrong so i'm fixing it but i would have liked to be sure to fix the problem :/

fix(mongodb): use correct args when calling mongodb driver #402

---

detectors/node/opentelemetry-resource-detector-github/package.json
metapackages/auto-instrumentations-node/package.json
metapackages/auto-instrumentations-web/package.json
package.json
packages/opentelemetry-host-metrics/package.json
packages/opentelemetry-id-generator-aws-xray/package.json
packages/opentelemetry-test-utils/package.json
plugins/node/opentelemetry-instrumentation-aws-lambda/package.json
plugins/node/opentelemetry-instrumentation-bunyan/package.json
plugins/node/opentelemetry-instrumentation-dns/package.json
plugins/node/opentelemetry-instrumentation-express/package.json
plugins/node/opentelemetry-instrumentation-graphql/package.json
plugins/node/opentelemetry-instrumentation-hapi/package.json
plugins/node/opentelemetry-instrumentation-ioredis/package.json
plugins/node/opentelemetry-instrumentation-ioredis/src/types.ts
plugins/node/opentelemetry-instrumentation-koa/package.json
plugins/node/opentelemetry-instrumentation-mongodb/package.json
plugins/node/opentelemetry-instrumentation-mysql/package.json
plugins/node/opentelemetry-instrumentation-net/package.json
plugins/node/opentelemetry-instrumentation-pg/package.json
plugins/node/opentelemetry-instrumentation-pino/package.json
plugins/node/opentelemetry-instrumentation-redis/package.json
plugins/node/opentelemetry-instrumentation-restify/package.json
plugins/node/opentelemetry-instrumentation-winston/package.json
plugins/web/opentelemetry-instrumentation-document-load/package.json
plugins/web/opentelemetry-instrumentation-user-interaction/package.json
plugins/web/opentelemetry-plugin-react-load/package.json
propagators/opentelemetry-propagator-aws-xray/package.json
propagators/opentelemetry-propagator-grpc-census-binary/package.json
propagators/opentelemetry-propagator-ot-trace/package.json

Update gts, eslint, typescript and hapi dependencies

---

examples/restify/package.json

fix: install restify instrumentation in it's example

---

examples/graphql/package.json
plugins/node/opentelemetry-instrumentation-graphql/README.md

- #485 
- I took the documentation of the optional constructor params from the source code and placed it in a nice markdown table. 
- I added the note @obecny wrote here https://github.com/open-telemetry/opentelemetry-js-contrib/issues/485#issuecomment-842584700 
- I added a link for graphql examples
Is there anything else I can do in order to improve the docs?
Closes #485

docs(instrumentation-graphql): improve README.md

---

.github/component_owners.yml

- PR authors are spammed by automatic dependency updates
- Ignore renovate-bot

chore: ignore renovate-bot for component owners

---

.github/component_owners.yml

- Adding myself to owner
- sorted packages alphabetically so it is easier to maintain and add new things

Adding myself to owner

---

examples/express/server.js
examples/express/tracer.js

Fixes #651 where documentation was missing on how to exclude certain routes from ExpressJS instrumentation. This was not trivial due to the dependency on HTTP instrumentation. 
By having this example I hope to help people, so they don't have to figure this out themselves.

Update express example to include route filtering

---

README.md

A few packages were moved to experimental upstream, this fixes links to them in the README.

Fix links to experimental instrumentation packages

---

detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEc2Detector.ts

fix: increase ec2 resource detector timeout

---

plugins/node/opentelemetry-instrumentation-aws-sdk/src/services/sqs.ts

- Removed unused consts in `aws-sdk` instrumentation.

chore(aws-sdk): remove unused consts

---

.github/workflows/unit-test.yml

chore: update actions/checkout to v2

---

examples/react-load/react/README.md
examples/react-load/react/docker/collector-config.yaml
examples/react-load/react/docker/docker-compose.yaml
examples/react-load/react/package.json
examples/react-load/react/src/web-tracer.js

- I wasn't able to run the React Load plugin example, this PR fixes that
- updates the config
- uses a more recent version of `opentelemetry-collector-contrib`
- adds missing dependencies
- updates the README
- sets the service name for the example

fix(examples): fix React Load plugin example

---

README.md

Contributors image is missing from readme
Added contributors image to readme

chore: Added contributors image to readme

---

.github/workflows/release-please.yml

Update release please so the overrides in PRs like #913 work

chore: update release-please

---

plugins/node/opentelemetry-instrumentation-aws-sdk/README.md

docs(aws-sdk): correct links to SNS/SQS/Lambda md files

---

plugins/node/opentelemetry-instrumentation-express/README.md

- `examples` in Readme is pointing to a non-existing path which is resulting in 404- Page not found.
- Corrected examples url.

chore(readme): corrected examples url

---

detectors/node/opentelemetry-resource-detector-instana/README.md

README fix
ENV variable was wrong

chore(resource-detector-instana): fixed incorrect README env variable

---

plugins/node/opentelemetry-instrumentation-ioredis/README.md

chore(ioredis): document unsupported v5

---

plugins/node/opentelemetry-instrumentation-pino/src/instrumentation.ts

Fixes #1203 
- Adds a debug log message when we patch the pino module

fix: Add applying patch debug log to pino module

---

renovate.json

#313 
Try once more to fix renovate config...
Refs: #1265, #1246

fix: correct Otel renovate config

---

.github/component_owners.yml

add haddasbronfman as a component owner of MySQL. 
(after I contributed this metric to mysql - #1220 )

fix(mysql): add haddasbronfman as component owner of mysql

---

packages/opentelemetry-host-metrics/src/enum.ts
packages/opentelemetry-host-metrics/src/metric.ts
packages/opentelemetry-host-metrics/src/stats/common.ts
packages/opentelemetry-host-metrics/src/types.ts
packages/opentelemetry-host-metrics/test/metric.test.ts

- Add Process Metrics defined in https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/process-metrics.md#process

feat(host-metrics): Add process metrics

---

.github/component_owners.yml

What it says on the tin
/cc @basti1302 @kirrg001

chore: add instana resource detector owners

---

plugins/web/opentelemetry-plugin-react-load/README.md

chore: mark plugin react load unmaintained

---

plugins/node/opentelemetry-instrumentation-connect/README.md

chore: mark plugin connect unmaintained

---

plugins/node/opentelemetry-instrumentation-dns/README.md

chore: mark plugin dns unmaintained

---

plugins/node/opentelemetry-instrumentation-hapi/README.md

chore: mark plugin hapi unmaintained

---

plugins/node/opentelemetry-instrumentation-koa/README.md

chore: mark plugin koa unmaintained

---

plugins/web/opentelemetry-instrumentation-user-interaction/src/instrumentation.ts

```parentSpan?: api.Span | undefined``` is the same as ```parentSpan?: api.Span``` and add the field to the JSDoc.
-

refactor: Fix typing and JSDoc

---

metapackages/auto-instrumentations-node/src/index.ts

Better align with the other exports.
Follow-up to #1772.

refactor(auto-instrumentations-node): Name export getResourceDetectors

---

CHANGELOG.md

docs: clarify in top-level changelog where recent changelog content is

---

plugins/node/opentelemetry-instrumentation-knex/README.md

The instrumentation config is just a type, not a class

docs(instr-knex): Fix knex instrumentation example

---

metapackages/auto-instrumentations-node/README.md

docs(auto-instrumentations-node): fix typo in code example

---

plugins/node/opentelemetry-instrumentation-ioredis/src/types.ts

- The link is broken for viewing the documentation of the `@opentelemetry/instrumentation-ioredis` options.
- Add a new link to what I think the old one was pointing towards, please correct me if I'm wrong here.

chore(docs): update redisio instrumentation docs link

---

plugins/node/instrumentation-undici/README.md

Fix NPM badge in README.md.
-
-

docs(undici): Fix NPM badge in README.md.

---

plugins/node/opentelemetry-instrumentation-redis-4/src/instrumentation.ts

fix(instrumentation-redis-4): avoid crash from incorrect this._diag ref

---

.github/workflows/codeql-analysis.yml

- aligns CodeQL runs with SIG Security recommendations (see https://github.com/open-telemetry/sig-security/issues/15)
- references https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1751

ci: align codeql settings with Security SIG recommendations

---

plugins/node/opentelemetry-instrumentation-router/README.md

- Router instrumentation import in the documentation

docs(instrumentation-router): correct import statement

---

metapackages/auto-instrumentations-node/test/register.test.ts
metapackages/auto-instrumentations-node/test/test-app/app-server.js

fix(auto-instrumentations-node): correct typo

---

.github/component_owners.yml

chore: add raphael-theriault-swi to component owners for express and mysql2

---

.github/component_owners.yml

Resolves: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2714

chore: Add `onurtemizkan` as `mongodb` component owner.

---

package-lock.json
plugins/node/opentelemetry-instrumentation-mongodb/package.json

Refs: #2757 
- remove tests for v3 as a temporary solution

test(instr-mongodb): remove tests for v3 to avoid CI failures

---

plugins/node/opentelemetry-instrumentation-router/src/instrumentation.ts

refactor(instrumentation-router): update semconv usage to ATTR_ exports

---

plugins/node/opentelemetry-instrumentation-pino/test/pino.test.ts

test(instrumentation-pino): update semconv usage to ATTR_ exports

---

plugins/node/opentelemetry-instrumentation-fastify/src/instrumentation.ts
plugins/node/opentelemetry-instrumentation-fastify/test/instrumentation.test.ts

refactor(instrumentation-fastify): update semconv usage to ATTR_ exports

---

detectors/node/opentelemetry-resource-detector-instana/README.md
detectors/node/opentelemetry-resource-detector-instana/package.json
detectors/node/opentelemetry-resource-detector-instana/src/detectors/InstanaAgentDetector.ts
detectors/node/opentelemetry-resource-detector-instana/src/semconv.ts

refactor(resource-detector-instana): update semconv usage to ATTR_ exports

---

examples/connect/.eslintrc.js
examples/connect/.npmrc
examples/connect/client.js
examples/connect/package.json
examples/connect/server.js
examples/connect/tracing.js

Refs: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2891

chore(examples): lint examples/connect using shared top-level eslint config

---

packages/instrumentation-document-load/test/documentLoad.test.ts

- Remove unnecessary code
- Small typo in document-load instrumentation test file

chore: typo in document-load instrumentation

---

packages/instrumentation-mongodb/test/mongodb-v3.test.ts

- Fix a flaky test in mongodb.
-

test(mongodb): close the client to avoid affecting other tests

---

packages/instrumentation-koa/test/koa.test.ts

test(instrumentation-koa): update semconv usage to ATTR_ exports

---

packages/instrumentation-knex/src/instrumentation.ts
packages/instrumentation-knex/src/semconv.ts

chore(instrumentation-knex): update semconv usage to ATTR_ exports

---

package-lock.json
packages/instrumentation-tedious/package.json
packages/instrumentation-tedious/src/instrumentation.ts
packages/instrumentation-tedious/src/semconv.ts
packages/instrumentation-tedious/test/instrumentation.test.ts

chore(instrumentation-tedious): update semconv usage to ATTR_ exports

---

packages/instrumentation-net/package.json
packages/instrumentation-net/src/instrumentation.ts
packages/instrumentation-net/src/semconv.ts
packages/instrumentation-net/src/utils.ts
packages/instrumentation-net/test/connect.test.ts
packages/instrumentation-net/test/utils.ts

chore(instrumentation-net): update semconv usage to ATTR_ exports

---

renovate.json

And I'm assuming Amir would like to be off this assignee-list.
Refs: https://github.com/open-telemetry/opentelemetry-js/pull/5923

chore: Trent can help review/merge renovate PRs

---

packages/instrumentation-mysql2/.tav.yml

test(instrumentation-mysql2): fix error in .tav.yml that resulted in no command to run
