open-telemetry/opentelemetry-js-contrib

plugins/node/opentelemetry-plugin-pg/src/pg.ts
Looks like for some reason pg-pool tests fail now because pg is not checking if query is already wrapped. Either pg-pool updated or something about the way tests are running changed due to new project structure. Either way, testing to see if a query is already wrapped is a good check.
=> Prevent double wrapping pg pool query

plugins/node/opentelemetry-plugin-ioredis/README.md, plugins/node/opentelemetry-plugin-ioredis/src/ioredis.ts, plugins/node/opentelemetry-plugin-ioredis/src/types.ts, plugins/node/opentelemetry-plugin-ioredis/src/utils.ts, plugins/node/opentelemetry-plugin-ioredis/test/ioredis.test.ts
IORedis plugin currently serializes the command name and arguments in the `db.statement` tag. This may yield to a big payload serialized inside the tag (for example, while `mget`ting many values or `set`ting large json objects). It may also be an issue when data saved inside Redis should not be accessible inside logs/traces. 
This PR adds an optional function inside the configuration that can be used to define a custom serialization function for `db.statement`. The function will receive cmdName and cmdArgs and will return a serialized string.
With this, one may decide (for example) to serialize only the `cmdName` for specific commands, or to have a separate handling for each command.
First contribution to the project so I hope I have done everything right :D
=> feat(opentelemetry-plugin-ioredis): provide a custom serializer fn for db.statement

examples/grpc-census-prop/README.md, examples/grpc-census-prop/capitalize_client.js, examples/grpc-census-prop/capitalize_server.js, examples/grpc-census-prop/combination2.md, examples/grpc-census-prop/combination4.md, examples/grpc-census-prop/package.json, examples/grpc-census-prop/protos/defs.proto, examples/grpc-census-prop/tracer.js, examples/grpc-census-prop/tracer_census.js, propagators/opentelemetry-propagator-grpc-census-binary/README.md
Signed-off-by: Kelly, Niall <Niall.Kelly@fmr.com>
Provide an example that verifies the new [propagator-grpc-census-binary](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/master/propagators/opentelemetry-propagator-grpc-census-binary) propagator.
During the review of PR #39 @mayurkale22 asked whether there was an example to verify the new propagator. This PR is to add that example.
The example started out based on the existing `grpc_dynamic_codegen` example - it makes similar gRPC calls.  Depending on environment variables, the client and server can be instrumented with either OpenTelemetry (with varying propagators) or OpenCensus. This allows us to test various combinations and understand when the binary propagator is useful.
The README contains extra information about …
=> feat: add gRPC Census Example

plugins/node/opentelemetry-plugin-ioredis/package.json, plugins/node/opentelemetry-plugin-ioredis/src/utils.ts, plugins/node/opentelemetry-plugin-ioredis/test/ioredis.test.ts
I've also fixed a missing dep in `test-utils` which was making my local install fail.
=> improv(ioredis): require parent span

plugins/web/opentelemetry-plugin-user-interaction/package.json, plugins/web/opentelemetry-plugin-user-interaction/src/userInteraction.ts, plugins/web/opentelemetry-plugin-user-interaction/test/userInteraction.test.ts
- Partly fixes this:
https://github.com/open-telemetry/opentelemetry-js/issues/1206
For full fix another PR is needed from sdk
https://github.com/open-telemetry/opentelemetry-js/pull/1209
- it run the task in active zone preserving the spawned zone instead of root zone
=> chore: fixing running task in a proper zone preserving the active zone

plugins/node/opentelemetry-plugin-pg-pool/package.json
- Remove `/node` from dependencies
- Move `/tracing` to devDependencies
=> chore(pg-pool): remove unused dependencies

.github/workflows/lint.yml, plugins/web/opentelemetry-plugin-user-interaction/src/userInteraction.ts, plugins/web/opentelemetry-plugin-user-interaction/test/userInteraction.nozone.test.ts
We need to patch removeEventListener in order to compensate for wrapping callbacks passed to addEventListener.
=> fix: patch removeEventListener to properly remove patched callbacks

plugins/web/opentelemetry-plugin-user-interaction/src/userInteraction.ts, plugins/web/opentelemetry-plugin-user-interaction/test/helper.test.ts, plugins/web/opentelemetry-plugin-user-interaction/test/userInteraction.nozone.test.ts
- Clean up span naming to OpenTelemetry specifications (existing names are discouraged as having high cardinality)
- Centralize logic for what event types to allow, and allow `dblclick` as well as `click`
- (Bad form, but blergh): forgot to unpatch removeEventListener from yesterday's work.
=> chore: clean up span naming

plugins/node/opentelemetry-plugin-pg/README.md, plugins/node/opentelemetry-plugin-pg/src/pg.ts, plugins/node/opentelemetry-plugin-pg/src/types.ts, plugins/node/opentelemetry-plugin-pg/src/utils.ts, plugins/node/opentelemetry-plugin-pg/test/pg.test.ts, plugins/node/opentelemetry-plugin-pg/test/utils.test.ts
This PR solves issue #11, that reports the PostgreSQL plugin must not log `pg.values` by default because they may contain sensitive data such as user credentials.
1. I fixed eslint warnings found in master.
1. I refactored the `PgClientExtended` type to inherit directly from `pgTypes.Client` instead of intersect them all the time.
1. I documented arguments of several methods of `utils.ts` to avoid generic types (`...args: unknown[]`)
1. I renamed `PgPluginQueryConfig` interface to `NormalizedQueryConfig` ([based on the plugin](https://github.com/brianc/node-postgres/blob/2ef55503738eb2cbb6326744381a92c0bc0439ab/packages/pg/lib/utils.js#L157)) to avoid confusion.
1. I changed implementation to log `pg.values` only when `enhancedDatabaseReporting` ([standard …
=> feat(opentelemetry-plugin-pg): omit pg.values by default

plugins/node/opentelemetry-plugin-mongodb/package.json, plugins/node/opentelemetry-plugin-mongodb/src/mongodb.ts, plugins/node/opentelemetry-plugin-mongodb/src/types.ts, plugins/node/opentelemetry-plugin-mongodb/test/utils.ts
- partially #116
- adhering to spec, worth noting: split `ns` to populate `db.name` and  `db.mongodb.collection` attributes
=> [mongodb] implement semantic db conventions

propagators/opentelemetry-propagator-grpc-census-binary/package.json, propagators/opentelemetry-propagator-grpc-census-binary/src/GrpcCensusPropagator.ts, propagators/opentelemetry-propagator-grpc-census-binary/test/GrpcCensusPropagator.test.ts, propagators/opentelemetry-propagator-jaeger/package.json, propagators/opentelemetry-propagator-jaeger/src/JaegerHttpTracePropagator.ts
- new TextMapPropagator interface (JaegerHttpTracePropagator and GrpcCensusPropagator)
- Use lastest version of opentelemetry-js (0.11.0) and replace HttpTextPropagator with TextMapPropagator.
- Change Context Object on GrpcCensusPropagator test.
- Delete useless devDependencies
=> fix: new version with TextMapPropagator interface

plugins/node/opentelemetry-plugin-redis/src/redis.ts, plugins/node/opentelemetry-plugin-redis/src/types.ts, plugins/node/opentelemetry-plugin-redis/src/utils.ts
- n/a
- Removing unneeded type `RedisPluginStreamTypes`
- only import required type from redis where applicable
- prefer import type where applicable
=> redis cleanup

plugins/node/opentelemetry-plugin-ioredis/src/ioredis.ts, plugins/node/opentelemetry-plugin-ioredis/src/types.ts, plugins/node/opentelemetry-plugin-ioredis/src/utils.ts
- n/a
- Removing unneeded type `IoredisPluginClientTypes`
- prefer `import type` where applicable
=> Ioredis cleanup

plugins/node/opentelemetry-plugin-express/src/express.ts, plugins/node/opentelemetry-plugin-express/test/express.test.ts
I was hesitant of implement it like this from the start (for performance reason since we are adding a listener for every *async* layer) but seeing the half-broken (timing are not accurate) spans reporting, i think it's better like this for end user.
=> fix(express): listen for `finish` event on response for async express layer #107

plugins/node/opentelemetry-plugin-redis/src/redis.ts
Support version 3.x of redis.
This could resolve issue #214
=> Allow redis version 3.0.0 and above

plugins/node/opentelemetry-plugin-mysql/src/mysql.ts, plugins/node/opentelemetry-plugin-mysql/src/utils.ts, plugins/node/opentelemetry-plugin-mysql/test/mysql.test.ts
- #206 
- Ensured that the span name is always a string. The approach differs when the query is a string vs an object:
- for string, use the verb 
- for an object, use the sql string without the templated variable
- Also replaced deprecated `equals` method in tests
=> [mysql] fix: ensure span name is a string to avoid [object Object] as span name

README.md
- Missing `@opentelemetry/instrumentation-graphql` link
- Add `@opentelemetry/instrumentation-graphql` link
=> docs(readme): add @opentelemetry/instrumentation-graphql

propagators/opentelemetry-propagator-jaeger/src/JaegerHttpTracePropagator.ts, propagators/opentelemetry-propagator-jaeger/test/JaegerHttpTracePropagator.test.ts
- #267 - `.fields()` is missing in `JaegerHttpTracePropagator`, but required by `TextMapPropagator`
- adds `.fields()` to jaeger propagator
=> fix: missing .fields() method in jaeger propagator

plugins/node/opentelemetry-instrumentation-graphql/src/types.ts, plugins/web/opentelemetry-plugin-document-load/src/documentLoad.ts, plugins/web/opentelemetry-plugin-document-load/test/documentLoad.test.ts
- When performance.getEntriesByType is undefined error is thrown(and fallback performance.timing is not used). This happens in Safari 10.1 for example where getEntriesByType is undefined but performance.timing is available.
- Check if performance.getEntriesByType is present before using it.
=> fix(plugin-document-load): check if getEntriesByType is available before using it

plugins/node/opentelemetry-instrumentation-graphql/README.md
This caused me some confusion because they node-sdk doesn't give me a tracer provider to pass in here.  But it turned out I don't have to call this at all.
=> Update GraphQL README to note `setTracerProvider` is optional

.github/workflows/codeql-analysis.yml
Follow up to issue https://github.com/open-telemetry/oteps/issues/144
[CodeQL](https://github.com/github/codeql-action) is GitHub's static analysis engine which scans repos for security vulnerabilities. As the project grows and we near GA it might be useful to have a workflow which checks for security vulnerabilities with every PR so we can ensure every incremental change is following best development practices. Also passing basic security checks will also make sure that there aren't any glaring issues for our users.
* This PR adds [CodeQL](https://github.com/github/codeql-action) security checks to the repo
* After every run the workflow uploads the results to GitHub. Details on the run and security alerts will show up in the `security` tab of this repo.
**Workflow Triggers**
* daily …
=> Add CodeQL Security Scans

plugins/node/opentelemetry-plugin-express/src/express.ts, plugins/node/opentelemetry-plugin-express/test/express.test.ts
Fixes https://github.com/open-telemetry/opentelemetry-js-contrib/issues/258
When a middleware is calling the callback synchronous inside the middleware the span was already ended and the added `finish` listener below was never removed.
=> fix(express): listener leak

plugins/node/opentelemetry-plugin-ioredis/test/ioredis.test.ts
ioredis tests run parallel for serverl node versions using the same redis instance.
Add a random part to keys to avoid that one run impacts others.
Additionally improve lua test asserts as the script may be already cached by redis resulting in one span less.
=> fix: avoid races because of parallel ioredis tests

plugins/node/opentelemetry-plugin-ioredis/package.json, plugins/node/opentelemetry-plugin-mongodb/package.json
These dependencies are imported at runtime but were only declared as
devDependencies.  This causes problems for people using these
packages with yarn pnp.
=> fix: move semantic-conventions to regular dependencies

plugins/web/opentelemetry-instrumentation-document-load/README.md
- The import is missing
- Add missing import
=> docs(readme): add missing import

README.md, metapackages/auto-instrumentations-node/README.md, metapackages/plugins-node-core-and-contrib/README.md, packages/opentelemetry-host-metrics/README.md, plugins/node/opentelemetry-instrumentation-dns/README.md, plugins/node/opentelemetry-instrumentation-express/README.md, plugins/node/opentelemetry-instrumentation-graphql/README.md, plugins/node/opentelemetry-instrumentation-hapi/README.md, plugins/node/opentelemetry-instrumentation-ioredis/README.md, plugins/node/opentelemetry-instrumentation-koa/README.md, plugins/node/opentelemetry-instrumentation-mongodb/README.md, plugins/node/opentelemetry-instrumentation-mysql/README.md, plugins/node/opentelemetry-instrumentation-net/README.md, plugins/node/opentelemetry-instrumentation-pg/README.md, plugins/node/opentelemetry-instrumentation-redis/README.md, plugins/node/opentelemetry-plugin-dns/README.md, plugins/node/opentelemetry-plugin-express/README.md, plugins/node/opentelemetry-plugin-ioredis/README.md, plugins/node/opentelemetry-plugin-mongodb/README.md, plugins/node/opentelemetry-plugin-mysql/README.md, plugins/node/opentelemetry-plugin-pg-pool/README.md, plugins/node/opentelemetry-plugin-pg/README.md, plugins/node/opentelemetry-plugin-redis/README.md, plugins/web/opentelemetry-instrumentation-document-load/README.md, plugins/web/opentelemetry-instrumentation-user-interaction/README.md, plugins/web/opentelemetry-plugin-react-load/README.md, propagators/opentelemetry-propagator-grpc-census-binary/README.md, propagators/opentelemetry-propagator-jaeger/README.md, propagators/opentelemetry-propagator-ot-trace/README.md
more cleanups and fixes around links
removing gitter in favour of github discussions
=> chore: fixing broken links, updating to correct base url, replacing gitter with github discussions

plugins/node/opentelemetry-instrumentation-net/src/net.ts, plugins/node/opentelemetry-instrumentation-net/test/utils.ts
From the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spankind):
* `CLIENT` Indicates that the span describes a synchronous request to some remote service. This span is the parent of a remote SERVER span and waits for its response.
However there is no corresponding server span for `connect`. Thus I think the least spec violating span kind for `connect` should be `INTERNAL`.
Change span kind of `connect` from `CLIENT` to `INTERNAL`.
=> fix: net instrumentation - change span kind of connect to internal

plugins/node/opentelemetry-instrumentation-hapi/package.json, plugins/web/opentelemetry-instrumentation-user-interaction/package.json
Fix compilation issues by pinning @hapi/podium to 4.1.1 as later version has it's own typings which is not compatible with remaining dependencies.
=> fix: hapi compilation

examples/express/client.js, examples/express/package.json, examples/express/server.js, examples/express/tracer.js, plugins/node/opentelemetry-instrumentation-express/README.md
The express example was erroring and used soon-to-be-deprecated API. I'm bringing that up to date.
----
Mainly just removing the usage of the old plugins API and replacing that with `registerInstrumentations`. I also added logger configuration because especially for the newcomers it will definitely be helpful to see those messages and know how to configure the logger. Other than that it's functionally the same.
----
A question for the original express instrumentation developer(@vmarchaud, I believe): **Is it expected that if HTTP layer is not instrumented, express instrumentation is a no-op? Should we document that? Error? Somehow make HTTP instrumentation a dependency for express?**
If that looks alright, I could work on others as well.
Fixes #376
=> document: fix express example

plugins/node/opentelemetry-instrumentation-net/package.json, plugins/node/opentelemetry-instrumentation-net/src/utils.ts
Use semantic-conventions package to bring in `PIPE` and `UNIX` attributes.
=> refactor(net): remove hardcoded values, use semantic conventions

plugins/node/opentelemetry-instrumentation-mongodb/test/mongodb.test.ts
The logic to skip MongoDB tests if there's no MongoDB instance running currently fails the tests if there isn't.
=> test: fix mongo test skip logic when there's no DB instance running

plugins/node/opentelemetry-instrumentation-express/README.md
As discussed in the meeting today, I think making this point clear helps enduser to understand what they _might_ be doing wrong if no spans are exported.
=> docs: Explicitly state that express instrumentation does not export spans without http instrumentation

metapackages/auto-instrumentations-node/package.json, packages/opentelemetry-test-utils/package.json, plugins/node/opentelemetry-instrumentation-aws-lambda/package.json, plugins/node/opentelemetry-instrumentation-bunyan/package.json, plugins/node/opentelemetry-instrumentation-dns/package.json, plugins/node/opentelemetry-instrumentation-express/package.json, plugins/node/opentelemetry-instrumentation-hapi/package.json, plugins/node/opentelemetry-instrumentation-ioredis/package.json, plugins/node/opentelemetry-instrumentation-koa/package.json, plugins/node/opentelemetry-instrumentation-mongodb/package.json, plugins/node/opentelemetry-instrumentation-mysql/package.json, plugins/node/opentelemetry-instrumentation-net/package.json, plugins/node/opentelemetry-instrumentation-pg/package.json, plugins/node/opentelemetry-instrumentation-pino/package.json, plugins/node/opentelemetry-instrumentation-redis/package.json, plugins/node/opentelemetry-instrumentation-restify/package.json, plugins/node/opentelemetry-instrumentation-winston/package.json, plugins/web/opentelemetry-instrumentation-document-load/package.json, plugins/web/opentelemetry-instrumentation-user-interaction/package.json, plugins/web/opentelemetry-plugin-react-load/package.json, propagators/opentelemetry-propagator-grpc-census-binary/package.json
we move to eslint recently therefore it seems time to remove some tslint plugins/extensions from dev-dependencies.
=> chore: remove tslint dependencies

packages/opentelemetry-test-utils/testUtils.ts, plugins/node/opentelemetry-instrumentation-pg/test/pg-pool.test.ts, plugins/node/opentelemetry-instrumentation-pg/test/pg.test.ts, plugins/node/opentelemetry-instrumentation-pg/test/types.ts, plugins/web/opentelemetry-instrumentation-document-load/test/documentLoad.test.ts
- Removing dependency on TimedEvent from api
- Fixes https://github.com/open-telemetry/opentelemetry-js-api/issues/37
=> chore: removing usage of timed event from api

plugins/node/opentelemetry-instrumentation-express/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-express/src/types.ts, plugins/node/opentelemetry-instrumentation-express/test/custom-config.test.ts, plugins/node/opentelemetry-instrumentation-express/test/express.test.ts, plugins/node/opentelemetry-instrumentation-express/test/ignore-all.test.ts, plugins/node/opentelemetry-instrumentation-koa/package.json, plugins/node/opentelemetry-instrumentation-koa/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-koa/test/koa.test.ts, plugins/node/opentelemetry-instrumentation-restify/package.json, plugins/node/opentelemetry-instrumentation-restify/src/constants.ts, plugins/node/opentelemetry-instrumentation-restify/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-restify/src/types.ts, plugins/node/opentelemetry-instrumentation-restify/test/restify.test.ts
=> feat: use rpcMetadata to update http span name #464

plugins/node/opentelemetry-instrumentation-mongodb/README.md, plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-mongodb/src/types.ts, plugins/node/opentelemetry-instrumentation-mongodb/test/mongodb.test.ts
- Add the ability to collect the response of a mongo action (as an optional configuration). This data can be used for monitoring purposes.
- Added `responseHook` configuration member which is called at the end of each mongo action
=> feat(mongo instrumentation): added response hook option

metapackages/auto-instrumentations-node/README.md
- #497 
- Added a summary of what the package does to the readme.
- Added a list of instrumentations the package loads to the readme.
- Fixed the example so it uses resource instead of serviceName.
=> docs(auto-instrumentations-node): improved readme

plugins/node/opentelemetry-instrumentation-mongodb/src/index.ts
- New types were introduced in this https://github.com/open-telemetry/opentelemetry-js-contrib/pull/533 but were not exported as part of the plugin. This PR exposes them on `index.ts`
- Added the new types `MongoDBInstrumentationExecutionResponseHook` and `MongoResponseHookInformation` to the export clause on `index.ts`
=> fix(mongo): added missing exported types

plugins/node/opentelemetry-instrumentation-aws-lambda/README.md, plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-aws-lambda/src/types.ts, plugins/node/opentelemetry-instrumentation-aws-lambda/test/integrations/lambda-handler.test.ts
- Today, Lambda instrumentation supports trace propagation only for X-Ray or HTTP headers. This enhancement allows to add a custom configuration for extracting the context from incoming events to the Lambda function. This will allow the instrumentation to support more event types, such as SQS, CloudWatch or Kinesis.
- Added `eventContextExtractor` config option to allow custom handling of events which carry the context in different ways. If not provided, a default context extractor is used and tries to pull the context from the HTTP headers - same as the behavior today.
=> feat(aws-lambda): added eventContextExtractor config option

plugins/node/opentelemetry-instrumentation-pino/package.json
- #591 
- upgrade @types/pino to 6.3.11
=> chore(deps): upgrade @types/pino to be compatible with latest sonic-stream types

renovate.json
Adapt renovate configuration to match core repo and bump API to ensure that peer-dependency gets updated.
Refs: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/599
=> chore: configure renovate to bump API

.github/component_owners.yml, .github/workflows/component-owners.yml
First official component owners @willarmiros and @NathanielRN
=> chore: add ownership for aws propagator

packages/opentelemetry-browser-extension-autoinjection/README.md
- The browser extension instructions for building from source did not work.
- I updated the name of the repository, the directory, and the name of the script to run.
=> docs: correct the build instructions

plugins/node/opentelemetry-instrumentation-mysql/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-mysql/test/index.test.ts
Signed-off-by: Simon Stone <simonstone1@gmail.com>
- The problem described in issue #561 
- The callback for `getConnection` is now bound to the active context before it is passed into the instrumented `mysql` code
=> fix(mysql): bind get connection callback to active context

.github/component_owners.yml
Just making use of the new component owner workflow for some instrumentations I've authored.
=> chore: add Rauno56 as the component owner of authored instrumentations

.github/component_owners.yml
I would like to suggest myself as component owner for the `ioredis` and `redis` instrumentations.
Been using them for quite some time, and also created a few PRs with fixes in the past.
Not sure who originally wrote them. Happy to share ownership with whoever wants to join, or close this PR if the ownership should be set on someone else.
=> chore: add component owners to redis and ioredis

.github/workflows/lint.yml, .github/workflows/unit-test.yml
- Since https://github.com/open-telemetry/opentelemetry-js-contrib/pull/614, CI unit test are built faster using lerna hoisting. This PR apply hoisting on `lint` action in order to improve CI time. 
- Hoising **lint** action.
=> ci: speed up lint workflow with hoisting 

.github/workflows/lint.yml
- After #648 lint started failing in CI due to "ESLint couldn't find the config "./node_modules/gts" to extend from".
Looks like `eslint.config.js` is [referencing a file in `node_modules`](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/eslint.config.js#L7) which is now not accessible.
- add `gts` to the `no-hoist` list only for linting workflow. this should fix the workflow I believe.
This PR is only for fixing the current CI issue, but for the long run, I suggest executing the linting from the repo root and not per package. This has the following advantages:
1. less configuration and setup per package in the monorepo (no need to install `gts`, repeated the lint scripts in package.json, and include `.eslintignore` and `.eslintrc.js` for each package again and again) …
=> fix: lint failure in ci due to hoisting

packages/opentelemetry-test-utils/package.json
When the test util was made public its publish config was not set
=> chore: set publishConfig for test utils

packages/opentelemetry-test-utils/README.md
Same thing as #669 but without the revert because the squash commit causes release-please to not see the change.
Co-Authored-By: Amir Blum <amir@aspecto.io>
=> feat: upstream mocha instrumentation testing plugin from ext-js (@blumamir) #621

plugins/node/opentelemetry-instrumentation-graphql/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-graphql/src/utils.ts
GraphQL inputs are frequently nested like:
```
{
"input": {
"value1": 1,
"value2": 2
}
}
```
Currently this would result the following call:
```
span.setAttribute("graphql.variables.input", Object({ value1: 1, value2: 2}))
```
But since `SpanAttribute` doesn't accept an `Object` type it silently fails
and doesn't add the attribute at all.
This PR goes depth-first into the nested structure and adds each
variable with the appropriate path like:
```
span.setAttribute("graphql.variables.input.value1", 1)
span.setAttribute("graphql.variables.input.value2", 2)
```
=> fix: adding nested input variables in graphql plugin

.github/workflows/unit-test.yml, plugins/node/opentelemetry-instrumentation-pino/.tav.yml, plugins/node/opentelemetry-instrumentation-pino/README.md, plugins/node/opentelemetry-instrumentation-pino/package.json, plugins/node/opentelemetry-instrumentation-pino/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-pino/src/types.ts, plugins/node/opentelemetry-instrumentation-pino/test/pino.test.ts
- When upgrading to the latest version of Pino (v7.x), the OpenTelemetry instrumentation doesn't work anymore
- There is a hard check on the Pino version in use to prevent errors in case of major upgrades. I tested with the latest Pino version and bumped that number.
=> feat(instrumentation-pino): bump supported pino version to v7.x

.github/workflows/lint.yml
Github Actions team updated their base ubuntu to ship with Node 16 instead of 14 like before, so we got an npm update that obviously broke the dependency resolution and resulted in broken deps install. I didn't have the time to (nor the will ahah)  to make it work with node 16 so i just downgraded to 14 :)
=> chore(ci): fix lint workflow

plugins/node/opentelemetry-instrumentation-graphql/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-graphql/test/graphql.test.ts
Fixes #750
Await promise resolution before calling endSpan
=> fix: early close of span with graphql execute

plugins/node/opentelemetry-instrumentation-mongodb/test/mongodb.test.ts, plugins/node/opentelemetry-instrumentation-mongodb/test/utils.ts
This fixes tests for mongodb versions 3.3 - 3.4.
We're currently running TAV tests for 37 versions, 8 of which do not pass because versions before 3.5 do not resolve the DNS name. This bypasses that and makes the tests pass on all of the supported versions
=> test: use `127.0.0.1` in mongo tests as the default host

plugins/node/opentelemetry-instrumentation-koa/.tav.yml, plugins/node/opentelemetry-instrumentation-koa/package.json
We claim support for `koa@^2.0.0`, but only test for one fixed version.
I'm adding TAV setup for `^2.7.0`(13 versions, 97.23% of the downloads) rather than the whole supported range `^2.0.0`(26 versions 99.12% of the downloads) because the older versions are released a while ago and seldom installed anymore. Testing 13 versions took just under a minute.
<details>
<summary>Stats</summary>
```
❯ nvds koa ^2.0.0 
Loading stats for koa
┌─────────┬──────────┬───────────┬──────────────────────────┬──────────────┬──────────┐
│ (index) │ version  │ downloads │           time           │     tags     │ ratio(%) │
├─────────┼──────────┼───────────┼──────────────────────────┼──────────────┼──────────┤
│    0    │ '2.13.1' │  536865   │ 2021-01-04T15:12:12.283Z │      []      │   40.7   │
│    1    │ …
```
=> test: test multiple versions of `koa`

plugins/node/opentelemetry-instrumentation-graphql/.tav.yml, plugins/node/opentelemetry-instrumentation-graphql/README.md, plugins/node/opentelemetry-instrumentation-graphql/package.json
We claim support for `graphql@14+`, but only test for one fixed version. GraphQL v16 released this October is not supported - tests fail. Issue [here](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/784).
I'm adding TAV setup for a sample of versions in the range(13 versions, 78.87% of the downloads):
- `^15.8.0`,
- `15.7.2`,
- `15.6.1`,
- `15.6.0`,
- `15.5.3`,
- `15.5.1`,
- `15.5.0`,
- `15.4.0`,
- `15.3.0`,
- `14.6.0`,
- `14.5.8`,
- `14.5.0`,
- `14.0.0`,
rather than the whole supported range `>=14 || <16`(38 versions, 86.14% of the downloads).
Testing 13 versions took around a minute.
<details>
<summary>Stats</summary>
```
❯ nvds graphql "^15.8.0 || 15.7.2 || 15.6.1 || 15.6.0 || 15.5.3 || 15.5.1 || 15.5.0 || 15.4.0 || 15.3.0 || 14.6.0 || 14.5.8 || 14.5.0 || 14.0.0" …
```
=> test: test multiple versions of `graphql`

.github/workflows/test-all-versions.yml, .github/workflows/unit-test.yml, plugins/node/opentelemetry-instrumentation-aws-lambda/package.json, plugins/node/opentelemetry-instrumentation-aws-sdk/package.json, plugins/node/opentelemetry-instrumentation-bunyan/package.json, plugins/node/opentelemetry-instrumentation-cassandra/package.json, plugins/node/opentelemetry-instrumentation-cassandra/test/cassandra-driver.test.ts, plugins/node/opentelemetry-instrumentation-connect/package.json, plugins/node/opentelemetry-instrumentation-dns/package.json, plugins/node/opentelemetry-instrumentation-express/package.json, plugins/node/opentelemetry-instrumentation-fastify/package.json, plugins/node/opentelemetry-instrumentation-generic-pool/package.json, plugins/node/opentelemetry-instrumentation-graphql/package.json, plugins/node/opentelemetry-instrumentation-hapi/package.json, plugins/node/opentelemetry-instrumentation-ioredis/package.json, plugins/node/opentelemetry-instrumentation-knex/package.json, plugins/node/opentelemetry-instrumentation-koa/package.json, plugins/node/opentelemetry-instrumentation-memcached/package.json, plugins/node/opentelemetry-instrumentation-mongodb/package.json, plugins/node/opentelemetry-instrumentation-mysql/package.json, plugins/node/opentelemetry-instrumentation-mysql2/package.json, plugins/node/opentelemetry-instrumentation-nestjs-core/package.json, plugins/node/opentelemetry-instrumentation-net/package.json, plugins/node/opentelemetry-instrumentation-pg/package.json, plugins/node/opentelemetry-instrumentation-pino/package.json, plugins/node/opentelemetry-instrumentation-redis/package.json, plugins/node/opentelemetry-instrumentation-restify/package.json, plugins/node/opentelemetry-instrumentation-router/package.json, plugins/node/opentelemetry-instrumentation-winston/package.json
The services in CI are not currently accessible.
The hostnames do not resolve because the step execution was recently moved from containers(which belong to the bridge network where the service names resolve) to the runner machine.
See c69c202a - @dyladan
The [docs](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idservices):
> If you configure the job to run directly on the runner machine and your step doesn't use a container action, you must map any required Docker service container ports to the Docker host (the runner machine). You can access the service container using localhost and the mapped port.
The above section from the docs makes total sense, however, I'm personally not clear on why is …
=> fix: use localhost for services in CI

plugins/node/opentelemetry-instrumentation-ioredis/.tav.yml, plugins/node/opentelemetry-instrumentation-ioredis/package.json, plugins/node/opentelemetry-instrumentation-ioredis/test/ioredis.test.ts
Some of the assertions are done in the hooks in the tests for `ioredis`.
1. The errors thrown in the hooks are eaten, so no benefit having them there,
2. Even if they aren't one of them was validating an ever-increasing counter, which can ever only be correct once,
3. Test for `scan` broke when there were more than 10 keys in the DB - not a problem when running on a clean DB every time, but happens locally when tests occasionally completely fail and the cleanup will not happen.
- Added `sinon` to move the assertions in the hooks outside of them.
- Tweaked `scan` tests with match and count parameters
- Narrowed down the TAV version set - if we expect devs to ever run them, it better not take an hour. It currently takes 2 minutes.
=> test: fix ioredis tests

release-please-config.json
#815 is currently blocked by tedious tests failing. Tedious test-utils package is not updated because it is not included in the release config. This also would prevent it from being released by the automation.
=> chore: add tedious to release config

plugins/node/opentelemetry-instrumentation-aws-sdk/src/services/sns.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/test/sns.test.ts
- When using SNS to publish message to a phone number, span name contain the phone number.
According messaging spec, [span name should be of low cardinality](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#span-name)
- Span name will be `phone_number send` when publishing SNS to a phone number. As I implemented in [ruby's instrumentation](https://github.com/open-telemetry/opentelemetry-ruby/blob/658440f2f749f151fde393ce1654803a816f1c38/instrumentation/aws_sdk/lib/opentelemetry/instrumentation/aws_sdk/messaging_helper.rb#L22-L23)
=> fix(aws-sdk): sns span name should be with low cardinality

plugins/node/opentelemetry-instrumentation-aws-sdk/src/aws-sdk.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/test/aws-sdk-v2.test.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/test/aws-sdk-v3.test.ts
- Add `http.status_code` attribute, as discussed in Ruby repo
https://github.com/open-telemetry/opentelemetry-ruby/issues/1094
=> feat(aws-sdk): add http status code attribute to aws sdk span

plugins/node/opentelemetry-instrumentation-graphql/package.json
Fixes #802
Move graphql to dependencies in order to avoid a compilation failure during lib check (instrumentation imports graphql when it is not installed). This is affecting all users of the metapackage which installs the instrumentation but does not install graphql which it depends on.
=> fix(graphql): move graphql to dependencies

plugins/node/opentelemetry-instrumentation-aws-lambda/README.md, plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-aws-lambda/src/types.ts, plugins/node/opentelemetry-instrumentation-aws-lambda/test/integrations/lambda-handler.test.ts
Implements feat #855 - it exposes the lambda context object to the custom event extractor to allow this to carry context.
- Changes the signature of the eventContextExtractor to add context as a second argument
- Passes this through in via _determineParent
- Updates tests and README
- [x ] Ran `npm run test-all-versions` for the edited package(s) on the latest commit if applicable.
=> feat: support using lambda context in the aws lambda context extractor

package.json, packages/opentelemetry-browser-extension-autoinjection/package.json
- When installing dependencies using `yarn` from the root folder, I got the following error:
```
lerna ERR! npm install exited 1 in '@opentelemetry/browser-extension-autoinjection'
lerna ERR! npm install stderr:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @opentelemetry/browser-extension-autoinjection@0.27.2
npm ERR! Found: eslint@8.7.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"8.7.0" from the root project
npm ERR!   peer eslint@"^7.32.0 || ^8.2.0" from eslint-config-airbnb-base@15.0.0
npm ERR!   node_modules/eslint-config-airbnb-base
npm ERR!     dev eslint-config-airbnb-base@"15.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || …
```
=> fix: update eslint-plugin-import to resolve conflicts

packages/opentelemetry-browser-extension-autoinjection/package.json
update eslint-plugin-json5 to 0.1.4 which support eslint v8
This problem: which happened when I 'npm install' from root
lerna info versioning independent
lerna info Bootstrapping 45 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in '@opentelemetry/browser-extension-autoinjection'
lerna ERR! npm install stderr:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @opentelemetry/browser-extension-autoinjection@0.27.3
npm ERR! Found: eslint@8.7.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"8.7.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0" from eslint-plugin-json5@0.1.3
npm ERR! …
=> fix(browser-extension-autoinjection): update eslint-plugin-json5 version to 0.1.4 

plugins/node/opentelemetry-instrumentation-winston/README.md
Fixes #870 
Updates README to flip in the example for the log hook. The source code has it as a span and then record for args. 
- [:heavy_check_mark:  ] Ran `npm run test-all-versions` for the edited package(s) on the latest commit if applicable.
=> fix(documentation): mixed up winston readme for hook

plugins/node/opentelemetry-instrumentation-aws-sdk/src/services/sqs.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/test/sqs.test.ts
- `messaging.operation` attribute values were not taking advantage of the constants defined in the semantic-conventions package
- use MessagingOperationValues constants everywhere for `messaging.operation` attribute values
=> chore: use MessagingOperationValues constants

plugins/node/opentelemetry-instrumentation-ioredis/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-ioredis/test/ioredis.test.ts
This is split out of #913 because ioredis tests seem to hang CI.
=> fix!(ioredis): net.peer.ip -> db.connection_string

plugins/node/instrumentation-tedious/test/instrumentation.test.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/src/services/dynamodb.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/test/dynamodb.test.ts, plugins/node/opentelemetry-instrumentation-ioredis/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-ioredis/test/ioredis.test.ts, plugins/node/opentelemetry-instrumentation-knex/src/utils.ts, plugins/node/opentelemetry-instrumentation-memcached/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-memcached/test/index.test.ts, plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-mysql/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-mysql/test/index.test.ts, plugins/node/opentelemetry-instrumentation-mysql2/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-mysql2/test/mysql.test.ts, plugins/node/opentelemetry-instrumentation-redis/src/utils.ts, plugins/node/opentelemetry-instrumentation-redis/test/redis.test.ts
- DbSystemValues constants were used in some places but not in others
- use DbSystemValues everywhere for `db.system` attribute values
=> chore: use db.system constants from semantic-conventions package

plugins/node/opentelemetry-instrumentation-mysql2/README.md, plugins/node/opentelemetry-instrumentation-mysql2/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-mysql2/src/types.ts, plugins/node/opentelemetry-instrumentation-mysql2/test/mysql.test.ts
- Adding support for a `responseHook`, that enables collecting the query result.
- Add a `responseHook` config, and add tests to verify its behavior.
=> feat: add mysql2 responsehook

plugins/node/opentelemetry-instrumentation-redis/README.md
- The readme states redis instrumentation support versions `>=2.6.0` which includes version 4. But in the code version 4 is not supported, not patched and not tested. 
- redis instrumentation - updated supported versions. documented v4 is not supported yet.
=> docs(redis): update readme supported versions

plugins/node/opentelemetry-instrumentation-winston/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-winston/src/internal-types.ts, plugins/node/opentelemetry-instrumentation-winston/test/winston.test.ts
Fixes #925
The winston instrumentation needs the winston types only internaly.
Move them into an internal file to avoid leaking it to end user.
=> fix: avoid leaking winston types

release-please-config.json
fs instrumentation release is skipped in #929 because it is missing from the config
=> chore: add fs to release config

.github/workflows/test-all-versions.yml, plugins/node/instrumentation-amqplib/package.json
- after amqplib is merged, the daily run of `test-all-versions` fails because I added the service only to `unit-test.yml` and forgot to add it to `test-all-versions.yml`.
- add the required rabbitmq service also to `test-all-versions.yml`. This should fix the CI.
=> fix(amqplib): add missing rabbit service to CI daily run

scripts/peer-api-check.js
https://github.com/open-telemetry/opentelemetry-js-contrib/pull/939 is failing because of the peer check.
It's an useful check, but should not be run on examples.
Instead of excluding example packages one-by-one in CI scripts, created a special case in the checking script to skip enforcing this.
=> chore: skip peer checking on packages that look like examples

plugins/node/instrumentation-tedious/test/instrumentation.test.ts
Someone(khm...) has left a typo into the tests forcing MSSQL test always to be run.
=> fix: remove forcing RUN_MSSQL_TESTS to be true in tests

plugins/node/opentelemetry-instrumentation-pino/README.md, plugins/node/opentelemetry-instrumentation-pino/package.json, plugins/node/opentelemetry-instrumentation-pino/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-pino/src/types.ts, plugins/node/opentelemetry-instrumentation-pino/test/pino.test.ts
- The log level isn't available in the config hook (it was added to the mixin function since v7.9.0)
- Propagate the log level to the hook
=> feat: send log level to pino hook

packages/opentelemetry-browser-extension-autoinjection/README.md
Fixes #905, this removes a link to my repository that contains old versions of the extension
Remove a section from README.md
Only a change for a md file, no code changes
There are releases of the extension at [Releases](https://github.com/open-telemetry/opentelemetry-js-contrib/releases?q=browser-extension-autoinjection&expanded=true), however they only contain the source code, what changes do I need to apply to have the extension build and put there similar to [here](https://github.com/svrnm/opentelemetry-browser-extension/releases), i.e. the two builds for manifest version 1 & 2 as zip files for people to use.
Side Note: there is also the option to publish those extension on https://chrome.google.com/webstore/category/extensions and https://addons.mozilla.org/de/firefox/, making it easy …
=> fix: remove link to browser extension to external repo.

detectors/node/opentelemetry-resource-detector-gcp/package.json
https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1000
Move @opentelemetry/core to dependencies
=> fix: move @opentelemetry/core to dependencies

plugins/node/opentelemetry-instrumentation-aws-sdk/.tav.yml
TAV runs take approximatelys 3 hours. Half of it is spent on testing different `aws-sdk` versions. Not a huge problem, but still quite out of balance and a realy problem since we expect devs to actually run TAV locally.
Update version ranges for TAV runs for `aws-sdk` instrumentation.
=> test: update TAV versions for aws-sdk instrumentation package

release-please-config.json
Our release step is failing. Don't know for a fact that it's because of the rate-limiting, but there are glues. Release Please could output rate limiting errors as "Server Errors".
Enabled [an option](https://github.com/googleapis/release-please/blob/d7d525f283f931dd999ca69228e71dd6adf9e0c3/docs/manifest-releaser.md) to slow API calls down.
=> chore(release-please): issue GitHub API requests sequencially

plugins/node/opentelemetry-instrumentation-redis/README.md
The Redis instrumentation already accepts several options on initialisation, in a similar manner to the IORedis instrumentation. Unlike in the IORedis instrumentation, however, these options are undocumented for the Redis instrumentation. This PR copies the relevant documentation about initialisation options from the IORedis instrumentation's README to the Redis one, tweaking it where the instrumentation libraries differ.
- Copy documentation on IORedis instrumentation's initialisation options to the Redis instrumentation's README.
- Do not copy any documentation relating to the `requestHook` option, as it is not supported by the Redis instrumentation.
- Amend the documentation to document differences in default values:
- In the IORedis instrumentation, the default `db.statement` …
=> docs(instrumentation-redis): add instrumentation options

plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts
- Unwrapping of the wrong object
- After checking if `moduleExports.Connection.prototype.command` is wrapped, we unwrap `moduleExports` and not `moduleExports.Connection.prototype`
=> fix: mongodb unwrapping

CONTRIBUTING.md
`npm run bootstrap` is ran as a `postinstall` lifecycle hook during `npm
install`, thus executing it as a separate step is not necessary.
See https://github.com/open-telemetry/opentelemetry-js-contrib/blob/8786cbe7163e552a4d9fc39609188236fd66c780/package.json#L16
=> docs: remove obsolete instruction

propagators/opentelemetry-propagator-ot-trace/src/OTTracePropagator.ts, propagators/opentelemetry-propagator-ot-trace/test/OTTracePropagator.test.ts
Fixes the way the `sampled` flag is read from the span context. The way it
is currently read will break when more flags are introduced. This is even
mentioned explicitly in the
[specification](https://www.w3.org/TR/trace-context/#trace-flags).
- check the flag bit independently instead of comparing the whole flags byte value with the SAMPLED_FLAG constant.
- add a unit test that show cases the issue (and breaks without the change in production code)
=> fix(propagator-ot-trace): read sampled flag correctly from span context

plugins/node/opentelemetry-instrumentation-memcached/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-memcached/test/index.test.ts
- Fixes https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1102
We have addressed the problem above by making the changes necessary and we can get the memcached value from the span attributes itself. 
- Removed query.type from the span name as it creates a high cardinality of span names.
- The span name will be memcached get or memcached set. (Open to change this span name)
=> fix(memcached): low cardinality span name

detectors/node/opentelemetry-resource-detector-docker/package.json, plugins/node/opentelemetry-instrumentation-express/examples/package.json, plugins/node/opentelemetry-instrumentation-koa/examples/package.json, plugins/node/opentelemetry-instrumentation-mongodb/package.json, plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts, tsconfig.base.json
There were some sub-packages that used the latest typescript version and caused errors against the deprecated @types/mongodb: 3.6.20 dependency.
1. Moved the deprecated MongoDB dependency to a devDependency:
* The use of `@types/mongodb` in the instrumentation itself was minor. 
All the places that used the MongoDB types were replaced with `any` as it applied in many other instrumentations,
in order to avoid the use of deprecated dependencies.
2. Aligned all typescript versions in the project to 4.3.5:
There were three packages that were used latest typescript version (duo to "^version):
* "koa-example"
* express-example
* @opentelemetry/resource-detector-docker
Also, we have to think about how to restrict those typescript version update changes.
=> fix: mongodb types fails to compile with latest tsc v4.8

plugins/node/opentelemetry-instrumentation-dns/test/integrations/dns-lookup.test.ts, plugins/node/opentelemetry-instrumentation-dns/test/integrations/dnspromise-lookup.test.ts
[Bug] DNS Lookup and Promise Lookup test for error NOT_FOUND failing #1136 
DNS resolution in local environment is exceeding 2 seconds (due to lots of fallback DNS servers) for invalid URL this is causing these 2 tests to timeout with the default 2 second delay.
Resolution:
Extend the timeout for these 2 tests so for environments where DNS resolution can take longer than expected the tests still pass.
=> ci: [Bug] DNS Lookup and Promise Lookup test for error NOT_FOUND failing #1136

.github/component_owners.yml
Added me to be the owner of the MongoDB instrumentation.
I am willing to take component owner responsibilities for this component.
List of my contribution to MongoDB instrumentation:
* https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1141
* https://github.com/open-telemetry/opentelemetry-js-contrib/pull/869
=> chore(mongodb): add mongodb instrumentation component owner

plugins/node/opentelemetry-instrumentation-pino/.tav.yml
Pinto test-all-versions for versions <8 fail the test-all versions.
Also, according to the documentation, the instrumentation does not support versions that are greater than ^7.11.
-
Remove the testing for version <8 and open a new issue to support versions <8
-
The failed Ci:
https://github.com/open-telemetry/opentelemetry-js-contrib/runs/8117913889?check_suite_focus=true
=> fix(pino): removed the tav for versions ^8

packages/opentelemetry-host-metrics/README.md
fixes https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1014
The readme example is updated to a working snippet
=> docs(fix): host metrics readme snippet

plugins/node/opentelemetry-instrumentation-express/src/instrumentation.ts
Fixes #1193 
Fixes #1209 
Express instrumentation does not pass a time to span start but does pass a time to span.end, which results in undefined behavior. Previous to https://github.com/open-telemetry/opentelemetry-js/pull/3134 this was not a problem as the span always used the same hrTimer that we expose in core. Now that we anchor clocks, it is possible for these clocks to be out of sync.
=> fix(express): use the same clock for span start and end

.github/workflows/release-please.yml
The check `if: ${{ steps.release.outputs.releases_created }}` does not seem to be working. Fortunately, `lerna publish from-package` already only releases packages which have had their versions updated. As a result, we should be able to release on any merge to main.
=> ci: always release packages when a release is merged

plugins/node/instrumentation-fs/src/constants.ts, plugins/node/instrumentation-fs/src/instrumentation.ts, plugins/node/instrumentation-fs/test/definitions.ts, plugins/node/instrumentation-fs/test/index.test.ts
`fs.exists` has an unusual signature with the callback never returning an error.
To get around that when using `util.promisify`, custom promisifing function is defined.
Our instrumentation doesn't take that into account.
Fixes #1185
Added separate patcher for `fs.exists` that is aware of the above and define a new custom promisifying function for our patched function.
=> fix(instrumentation-fs): fix `fs.exists` when it's util.promisified

plugins/node/opentelemetry-instrumentation-dns/src/utils.ts, plugins/node/opentelemetry-instrumentation-dns/test/integrations/dnspromise-lookup.test.ts
In #110 the `dns` promise based tests were reinstated for node 8 via a ["polyfill"-style function in the test source](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/110/files#diff-3060c03216ba47af1a62f232e8128a3844ab6e97ca67328f4c9c5ec4b5cfc7fcR36-R50) with
[this comment](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/110#discussion_r455406397).
It's unclear to me what exactly was being attempted here, since the net result of making all calls  in the test function funnel through this `lookupPromise()` function was that the functionality that was supposed to be tested (i.e. `dns.promises.lookup()` was no longer tested at all.
This may have been missed because code coverage was probably not run as part of CI then, but looking at code coverage now, the code …
=> fix(dns): remove lookupPromise polyfill for node8 dns promise tests 

plugins/node/opentelemetry-instrumentation-fastify/package.json, plugins/node/opentelemetry-instrumentation-fastify/src/types.ts
No need to bundle `fastify` with the instrumentation. `fastify` types are not exposed to users.
=> fix(fastify): move fastify to dev dependencies

plugins/node/opentelemetry-instrumentation-aws-sdk/.tav.yml
Once in a while, we need to reduce the number of aws-sdk versions to test with "test-all-versions".
They publish many versions and it takes too much time to test them all
=> test: reduce number of aws-sdk versions for tav

plugins/node/opentelemetry-instrumentation-koa/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-koa/src/types.ts, plugins/node/opentelemetry-instrumentation-koa/test/koa.test.ts
Unlike [the context given to the Express request hook](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-express/src/types.ts#L73-L80), the Koa request hook context does not contain information on whether the layer whose instrumentation is being intercepted by the request hook is a middleware layer or a router layer.
- Add the `layerType` to the context object passed to the `requestHook` interceptor function.
- Add the `layerType` property to the `KoaRequestInfo` context type.
- Add a check on the layer type to the unit tests.
=> feat(koa): add layer type to request hook context

plugins/node/instrumentation-dataloader/src/instrumentation.ts, plugins/node/instrumentation-mongoose/src/mongoose.ts, plugins/node/instrumentation-mongoose/src/utils.ts
Fixes #1217
Fixes #1218
- Cast Dataloaders module definitions to `InstrumentationNodeModuleDefinition<unknown>`
- Turned `patch` and `unpatch` methods on mongoose instrumentation private
- Cast the Collection argument in mongoose untils inside the function as opposed to having the type on the signature
=> fix: remove types of the instrumented libs form public apis

plugins/node/opentelemetry-instrumentation-graphql/package.json, plugins/node/opentelemetry-instrumentation-graphql/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-graphql/src/utils.ts, plugins/node/opentelemetry-instrumentation-graphql/test/graphql-adaptor.ts, plugins/node/opentelemetry-instrumentation-graphql/test/graphql.test.ts, plugins/node/opentelemetry-instrumentation-graphql/test/schema.ts
- fixes #1082 
The issue is that graphql resolvers can either be a promise or a sync function. Instrumentation wrapped each result with a promise (using `asyncSafeExecuteInTheMiddle`) which was confusing graphql, making it fail for sync runs, and changing the span times in a way that doesn't make sense (sync calls now overlapped).
- When wrapping graphql resolver, check if the result is a promise and handle promise and sync response accordingly.
I added test and run `test-all-versions` on the PR
=> fix(graphql): graphql instrumentation throw for sync calls

plugins/node/opentelemetry-instrumentation-aws-sdk/package.json
- fixes #1153 
- bump the aws-sdk instrumentation version to 0.32.0 so that it's higher than "0.25.0" which was released by mistake on 19/10/2021. [release on npm](https://www.npmjs.com/package/@opentelemetry/instrumentation-aws-sdk/v/0.25.0).
=> fix(aws-sdk): bump instrumentation version to align with previous release

plugins/node/opentelemetry-instrumentation-hapi/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-hapi/test/hapi-plugin.test.ts
I missed this in #1046.
HAPI plugins can be registered directly as objects, with `server.register(plugin)`. But they can also be registered as an array, with `server.register([plugin])`.
Right now, we only accept `server.register([{plugin: plugin}]);`, which doesn't match the hapi documentation.
See https://hapi.dev/tutorials/plugins/?lang=en_US#loading
Allow registering hapi plugins from an array when the object is passed directly, and they are not nested within a deeper object.
=> fix: allow hapi plugin from array to be registered as argument

.github/workflows/unit-test.yml, archive/opentelemetry-browser-extension-autoinjection/package.json, metapackages/auto-instrumentations-web/package.json, packages/opentelemetry-id-generator-aws-xray/package.json, plugins/web/opentelemetry-instrumentation-document-load/package.json, plugins/web/opentelemetry-instrumentation-long-task/package.json, plugins/web/opentelemetry-instrumentation-user-interaction/package.json, plugins/web/opentelemetry-plugin-react-load/package.json, propagators/opentelemetry-propagator-aws-xray/package.json, propagators/opentelemetry-propagator-instana/package.json, propagators/opentelemetry-propagator-ot-trace/package.json
- Contrib Browser tests are failing with out of memory issue #1248
- Make sure the same versions of webpack and karma-webpack are used for all packages
=> fix: address webpack memory issue for browser tests

plugins/node/opentelemetry-instrumentation-fastify/src/instrumentation.ts
Related to #1266 
Prior to this fix, typescript users that have the fastify instrumentation installed but do not have the `fastify` package installed would get compilation errors because typescript was expecting the `fastify` package to be present. This issue is bound to happen for anyone using the auto instrumentation feature.
- Mark all methods that use types from `fastify` as private in `instrumentation.ts`.
=> fix(instrumentation-fastify): stop using fastify types in public api

packages/opentelemetry-host-metrics/package.json, packages/opentelemetry-host-metrics/src/BaseMetrics.ts, packages/opentelemetry-host-metrics/src/metric.ts, packages/opentelemetry-host-metrics/test/metric.test.ts, renovate.json
Update host-metrics to use the GA version of metrics SDK and no longer use api-metrics.
Remove metrics packages from experimental OTel renovate config.
=> feat: use GA version of metrics

plugins/node/opentelemetry-instrumentation-fastify/package.json
Update fastify dev dependency  instrumentation-http to 0.34.0. Seems this slipped through in #1278
=> chore: update fastify dev-dependency instrumentation-http to 0.34.0

plugins/node/opentelemetry-instrumentation-pg/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-pg/src/internal-types.ts, plugins/node/opentelemetry-instrumentation-pg/src/utils.ts, plugins/node/opentelemetry-instrumentation-pg/test/pg.test.ts, plugins/node/opentelemetry-instrumentation-pg/test/utils.test.ts
The primary functional change in this PR is to address a number of issues with how the pg instrumentation was generating span names.
1. Before this PR, when the query being executed was a prepared statement with a `name`, the `name` was transformed first before it was put into the span's name. E.g., `client.query({ name: 'find user', text: 'SELECT * from user where id = ?', values: [1] })` would generate a span name of `pg.query:find`, because the string `'find user'` would be split on spaces and only the first word would be used. However, it's the full prepared statement name that constitutes the low cardinality identifier, so this commit now makes the span name: `pg.query:find user`.
2. Similarly, before this PR, the parsed out operation name wasn't normalized before using it in the …
=> fix: pg span names

plugins/node/opentelemetry-instrumentation-pg/README.md, plugins/node/opentelemetry-instrumentation-pg/package.json, plugins/node/opentelemetry-instrumentation-pg/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-pg/src/internal-types.ts, plugins/node/opentelemetry-instrumentation-pg/src/types.ts, plugins/node/opentelemetry-instrumentation-pg/src/utils.ts, plugins/node/opentelemetry-instrumentation-pg/test/pg.test.ts
Right now, it's possible to modify the span generated for a query after results are returned for the query, using the `responseHook`. However, it isn't possible to modify the span at the start of the query, based on the information available when the query is issued (i.e., the args passed to `client.query`), because that information isn't passed to the `responseHook`.
For my use case, I'm using Datadog and am tracing an app that issues relatively few distinct queries. Therefore, it makes sense to identify each query as a distinct Datadog "resource", by adding a `resource.name` attribute to each span, where the value of the attribute is the query text. However, this is currently impossible, because the query text isn't available in the `responseHook`, and there's no other hook where it is …
=> feat(pg): support hooking into span when query is started

plugins/node/opentelemetry-instrumentation-aws-sdk/.tav.yml
TAV builds for `aws-sdk` are breaking due to a incompatible/borken version of `aws-sdk`. Skip that in TAV runs.
=> ci: skip a broken aws-sdk version in TAV

plugins/node/opentelemetry-instrumentation-restify/README.md, plugins/node/opentelemetry-instrumentation-restify/src/index.ts, plugins/node/opentelemetry-instrumentation-restify/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-restify/src/internal-types.ts, plugins/node/opentelemetry-instrumentation-restify/src/types.ts, plugins/node/opentelemetry-instrumentation-restify/test/restify.test.ts
The `requestHook` config option allows custom span handling per request layer.
- Adds `requestHook` support so users can add custom handling on spans.
- It's inspired by how ~requestHook` is implemented in web instrumentations.
- The ~requestHook` user-defined function is called any time `_handlerPatcher` is executed.
=> feat(restify): add requestHook support

.github/component_owners.yml
- add haddasbronfman as component owner of openlemetry-redis-common
=> fix(component owner): add haddasbronfman as component owner of openlemetry-redis-common

metapackages/auto-instrumentations-node/src/utils.ts, metapackages/auto-instrumentations-web/src/utils.ts, plugins/node/instrumentation-dataloader/src/instrumentation.ts, plugins/node/instrumentation-fs/src/types.ts, plugins/node/opentelemetry-instrumentation-graphql/src/internal-types.ts
CI currently fails on lint workflow for a few days, and we can't merge approved PRs. I guess some transitive dependency was updated and change the prettier config/functioning.
I do not have time to understand where it comes from, but run `lint:fix` on the repo to make CI green again.
=> ci: fix lint

plugins/node/instrumentation-fs/README.md, plugins/node/instrumentation-fs/src/instrumentation.ts, plugins/node/instrumentation-fs/src/types.ts, plugins/node/instrumentation-fs/test/parent.test.ts
- The fs instrumentation, unlike other instrumentations, does not have a `requireParentSpan` option, in order to only trace calls to the fs module that happen in the context of a broader action. Applications might, for example, read some files during boot, which would rarely make for useful traces.
- Add a `requireParentSpan` option, which defaults to `false`. If set to `true`, calls to the fs module will not be instrumented unless the current active context has a span, so the fs instrumentation will never create a trace of its own.
=> feat(instrumentation-fs): require parent span

plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-aws-lambda/test/integrations/lambda-handler.force-flush.test.ts
…regardless how many providers are flushed
Signed-off-by: Anthony J Mirabella <a9@aneurysm9.com>
Defect identified in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1370#pullrequestreview-1289551665.
Combine all provider flush invocations to a single `Promise.all()` that can be resolved once.
=> fix(instrumentation/aws-lambda): Ensure callback is only called once

plugins/node/instrumentation-amqplib/src/amqplib.ts, plugins/node/instrumentation-amqplib/src/types.ts
I started getting type checking errors when using node auto instrumentation:
```
$ tsc --skipLibCheck false --incremental false
node_modules/@opentelemetry/instrumentation-amqplib/build/src/utils.d.ts:3:28 - error TS2307: Cannot find module 'amqplib' or its corresponding type declarations.
3 import type * as amqp from 'amqplib';
~~~~~~~~~
Found 1 error in node_modules/@opentelemetry/instrumentation-amqplib/build/src/utils.d.ts:3
```
Turns out that the compiled `utils.d.ts` imports `amqplib` directly which breaks. This worked fine before #1320 which moved `@types/amqplib` as a dev dependency. The PR adjusted most places where `amqplib` was imported but it missed one.
- Make `getConsumePatch`, `getConfirmedPublishPatch` and `getPublishPatch` in `AmqplibInstrumentation` private. They used to …
=> fix(amqplib): stop importing from `amqplib` directly in compiled types

plugins/node/opentelemetry-instrumentation-graphql/src/enums/AttributeNames.ts, plugins/node/opentelemetry-instrumentation-koa/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-koa/src/internal-types.ts, plugins/web/opentelemetry-instrumentation-document-load/src/enums/AttributeNames.ts, plugins/web/opentelemetry-instrumentation-document-load/src/instrumentation.ts, plugins/web/opentelemetry-instrumentation-long-task/src/instrumentation.ts
- The "component" attribute [was removed from semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/pull/447) back in Feb 2020, but some instrumentations were written before this change and still report this attribute.
- remove the "component" attribute from "@opentelemetry/instrumentation-document-load" and "@opentelemetry/instrumentation-long-task" as well as clean up some related dead code in other places
=> fix: remove component attribute from instrumentations

plugins/node/instrumentation-fs/test/fsPromises.test.ts, plugins/node/instrumentation-fs/test/fsPromisesHooks.test.ts
This PR removes unnecessary `supportsPromises` checks in `instrumentation-fs` tests, since we do not run tests for Node.js versions below 14.
Addresses https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1375#discussion_r1118094721.
N/A
=> chore(instrumentation-fs): remove node 14 promises check from tests

examples/connect/package.json
renovate bot complains regarding non existing instrumentation-connect version 0.24.0.
Use the best matching existing version instead to avoid this renovate issues.
=> chore: use existing instrumentation-connect version

plugins/node/opentelemetry-instrumentation-graphql/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-graphql/test/graphql.test.ts
Rename graphql "execute" spans to "<operation.type> <operation.name>" to conform to the [spec](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/instrumentation/graphql/).
In addition to conforming to the spec, this change can provide additional value for monitoring purposes. In cases where o11y providers generate metrics from pre-ingested traces (without all the attributes), the new naming convention makes it easier to group and filter metrics by operation type and name, since it is now reflected in the span name. This can be particularly useful for setting up monitors or alerts.
When operation name and type are determined within the execute span, `span.updateName()` is called.
The query steps other than "execute"'s spans are out of scope as they
do not …
=> fix(gql)!: conform GraphQL span name to spec

plugins/node/opentelemetry-instrumentation-mysql/package.json, plugins/node/opentelemetry-instrumentation-mysql/src/utils.ts
Remove unnecessary dependency on `mysql` package, which is only used in tests.
Moved `mysql` to dev dependencies.
=> chore(mysql): remove mysql from dependencies

examples/react-load/preact/docker/collector-config.yaml, examples/react-load/preact/docker/docker-compose.yaml, examples/react-load/preact/package.json, examples/react-load/preact/src/web-tracer.js
- Renovate bot is failing to create/update PRs as the `omnition/opentelemetry-collector-contrib:0.2.8` image has been removed from dockerhub. 
Due to restrictions on OAuth apps in the otel organization, and the fact that the logs dashboard is not supported with `forking-renovate`, we cannot access renovate bot logs, so I recreated an environment in a private organization and was able to find that the missing docker image causes the bot to skip any other steps.
This may be caused by a bug in forking-renovate, so if this PR fixes the issue, I'll open an issue on the renovate repository so that this can be investigated.
Fixes (hopefully) #1434 
- update the example to use an existing image
- to use an existing image, I also had to update the example to use a more recent OTel JS version, so I …
=> fix(preact-example): update example to use latest otelcol/js-core

.husky/commit-msg, renovate.json
Exclude examples from renovate runs because there is no CI to verify that they still work after the update.
As they are terrible outdated already any update is likely breaking them because some still use components not released anymore and therefore no compatibility to actual release without code change.
Refs: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1459
=> chore: exclude examples from renovate

detectors/node/opentelemetry-resource-detector-instana/README.md, detectors/node/opentelemetry-resource-detector-instana/package.json, detectors/node/opentelemetry-resource-detector-instana/src/detectors/InstanaAgentDetector.ts, detectors/node/opentelemetry-resource-detector-instana/test/InstanaAgentDetectorIntegrationTest.test.ts
Refs https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1459#issuecomment-1498805145
I do no have write permissions for renovate-bot:renovate/otel-core-experimental.
Feel free to close this PR and cherry-pick the commit.
The README files for all detectors needs to be updated too. Let me know if you want me to update them too.
=> chore(detectors/node): adapted breaking change in @opentelemetry/sdk-node@0.37.0

plugins/node/opentelemetry-instrumentation-mysql/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-mysql/test/index.metrics.test.ts
While reviewing this PR: #1170, there were to comments that were relevant to mysql metrics too:
1. regarding the [metric description](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1170/#discussion_r1172510542) 
2. regarding the [metric unit](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1170/#discussion_r1172506395)
1. the description was replaced to 'The number of connections that are currently in state described by the state attribute.'
2. the unit was replaced to {connection}
=> fix(mysql): metrics - align metrics description and unit to semconv

plugins/node/opentelemetry-instrumentation-mysql2/.tav.yml
- tav is failing on the main branch because of [this problem](https://github.com/open-telemetry/opentelemetry-js-contrib/actions/runs/4906701688/jobs/8761324293#step:9:20761).
I think it happens because mysql2 version3 doesn't have a 'pretest' command in the tav.yml (my fault because I added this version) and this is why it complains `Cannot find module '@opentelemetry/contrib-test-utils'`
- I added a 'pretest' command for version3 test like the other version (v1 & v2) have. 
adding a screenshot of the error in case the link won't work:
=> fix(mysql2-tav): add 'pretest' command to tav.yml for mysql2 version 3

eslint.config.js, plugins/node/opentelemetry-instrumentation-graphql/src/instrumentation.ts
Fixes #1433 
- Added `"@typescript-eslint/no-floating-promises": "error"` rule in the eslint config to match the core repo.
=> fix(eslint-no-floating-promises): added `no-floating-promises` rule to match the core repo

examples/web/examples/document-load/index.js, examples/web/examples/meta/index.js, examples/web/examples/user-interaction/index.js, examples/web/package.json
- The web examples used the deprecated exporter package `exporter-otlp-http`
- Switched the use of `exporter-otlp-http` to `exporter-traces-otlp-http` in the web examples and updated the other otel dependencies.
=> chore(examples-web): bump web examples dependencies and use exporter-trace-otlp-http

plugins/node/opentelemetry-instrumentation-nestjs-core/package.json
- in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1422 renovate tried to update only one @nestjs/core without taking into account other @nestjs/x libraries that also should be updated. this PR update all of them.
=> fix(nestjs): update dependency @nestjs/x to v9

.github/workflows/peer-api.yaml, .github/workflows/release-please-validate.yaml, .github/workflows/test-all-versions.pr.yml
- Our GitHub workflows pull the latest version of `lerna`, but `lerna` `v7` and up do remove `lerna bootstrap`.
- pins the same version (`5.5.2`) as in our top-level `package.json` for now to unblock PRs, I'll open a follow-up issue to upgrade to `lerna` `v7`. 
See also https://github.com/open-telemetry/opentelemetry-js/issues/3894, #1542
=> chore(ci): pin lerna in github workflows

.github/component_owners.yml
Per the recent [component ownership audit](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1478) and as discussed in the SIG on 6/14/23, @pkanal and I are volunteering to take over the ownership of this component.
@obecny If you would like to continue being the owner, please let us know.
=> chore: Update component owners for the Document Load web instrumentation

plugins/node/opentelemetry-instrumentation-fastify/package.json
- Looks like recent changes over at fastify desupported older versions of typescript, which breaks CI at the moment
- The PR pins the devDependency to `4.18.0` until https://github.com/fastify/fastify/issues/4873 is resolved
- if the resolution to this issue is that support will be restored, I'll unpin it again
- if the resolution to this issue is that support will **not** be restored, I'll look into alternative ways of testing newer versions of fastify (possibly via TAV).
=> fix(instrumentation-fastify): fix fastify typescript compilation issue

plugins/web/opentelemetry-instrumentation-document-load/package.json, plugins/web/opentelemetry-instrumentation-document-load/test/documentLoad.test.ts
- new @opentelemetry/sdk-trace-web@1.15.0 which omit secureConnectionStart if the request if using http => this break some test in @opentelemetry/instrumentation-document-load
- update minimum version of sdk-trace-web in instrumentation-document-load to 1.15.0
- update test to remove check for secureConnectionStart
=> fix(document-load): compatibility issue with @opentelemetry/sdk-trace-web@1.15.0

renovate.json
Currently, renovate bot groups all minor and patch version upgrades into one PR, which makes it difficult to handle problems when they occur. This PR separates minor and patch into 2 different rules as we have in [core](https://github.com/open-telemetry/opentelemetry-js/blob/main/renovate.json). 
* Create a rule for bumping all patch versions in one PR, excluding "prettier" (same as in [core](https://github.com/open-telemetry/opentelemetry-js/blob/main/renovate.json#L3C20-L3C20))
* Create a rule for all minor version upgrades, and requires #637 for minor version bumps
=> chore(renovate): split patch and minor rules

renovate.json
- use "widen" range strategy for `@opentelemetry/api`
- renovate bot tries to bump api, but we want to keep it compatible with older api versions
- run experimental updates every weekday
- we can release on any day of the week, so this way we don't need to wait for a week if renovate fails or we release on a Friday
=> chore(renovate): change strategy for @opentelemetry/api, run experimental update every weekday

packages/opentelemetry-sampler-aws-xray/package.json
align aws xray to use contrib-test-utils v0.34.0 as all other packages.
=> fix(aws-xray): align aws xray to use contrib-test-utils v0.34.0

plugins/node/opentelemetry-instrumentation-mysql2/package.json
- `sql-common` was accidentally listed as a dev dependency
- Moves it to dependencies
=> fix(instrumentation-mysql2): sql-common should be a dependency

plugins/node/instrumentation-cucumber/package.json, plugins/node/opentelemetry-instrumentation-restify/package.json
This PR replaces renovate #1607 but aligns the version also in instrumentation-restify where it was set with caret instead of pinned.
After this PR, the version for `@types/semver` is aligned across all the packages in this monorepo.
=> chore(deps): update dependency @types/semver to v7.5.0

plugins/node/opentelemetry-instrumentation-mongodb/src/types.ts
The type `V4Connection` re-introduced in #1170 is missing any type definitions or imports for `Document`, breaking the build with Typescript strict mode.
BREAKING CHANGE: removes the broken exported type `V4Connection`.
Fixes #1639
`V4Connection` in `types.ts` is not referenced anywhere (the type definition in `internal-types.ts` is used. So lets just drop this type definition.
=> fix(mongodb): remove broken type export `V4Connection`

plugins/node/opentelemetry-instrumentation-dns/package.json
#1646 fixed the version of "semver" in the repo, but I accidentally merged it without noticing that it pinned a regular dependency (not dev) to a specific version which does not follow our conventions as documented [here](https://github.com/open-telemetry/opentelemetry-js/blob/main/doc/GUIDELINES.md#third-party-library-dependencies).
This PR is to fix this. After it is merged, the "semver" versions in the repo should be aligned correctly
=> fix(instrumentation-dns): use caret range for semver regular dependency

packages/opentelemetry-test-utils/src/test-utils.ts
- Convert the output of run commands to a string that is readable.
- No need to `docker rm ...` test containers for `npm run test:local` usage because the `docker run --rm ...` option will remove them when stopped.
When running `npm run test:local` in some of the packages (e.g. in "plugins/node/opentelemetry-instrumentation-ioredis") there were a couple problems with the running of docker commands:
1. If one of the commands failed, the printed output would be a raw array of Buffer content, e.g.:
Before:
```
...
Failed run command: docker rm otel-redis
[
null,
<Buffer >,
<Buffer 45 72 72 6f 72 20 72 65 73 70 6f 6e 73 65 20 66 72 6f 6d 20 64 61 65 6d 6f 6e 3a 20 4e 6f 20 73 75 63 68 20 63 6f 6e 74 61 69 6e 65 72 3a 20 6f 74 65 ... 8 more bytes>
]
```
After:
```
...
Failed run command: …
```
=> chore(test-utils): improve handling of running docker containers

plugins/node/opentelemetry-instrumentation-nestjs-core/src/instrumentation.ts
Installing `@opentelemetry/instrumentation-nestjs-core` and using the NestJS instrumentation plugin produces a deprecation warning with Fastify for every request. This deprecation warning was introduced in Fastify [v4.23.0](https://github.com/fastify/fastify/releases/tag/v4.23.0).
Resolves #1698.
This PR prevents accessing the deprecated `routerPath` property in Fastify if `req.routeOptions.url` exists.
=> fix: prevent accessing deprecated Fastify property in NestJS instrumentation

plugins/node/opentelemetry-instrumentation-fastify/package.json, plugins/node/opentelemetry-instrumentation-fastify/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-fastify/src/utils.ts, plugins/node/opentelemetry-instrumentation-fastify/test/instrumentation.test.ts
Instrumentation has been using deprecated properties producing errors like `FastifyDeprecation: Request#context property access is deprecated. Please use "Request#routeConfig" or "Request#routeSchema" instead for accessing Route settings. The "Request#context" will be removed in fastify@5.`
https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1275
I've added getting deprecated properties from newly introduced `routeOptions` object in fastify request. It supports also old versions that doesn't have this object exposed. It has been introduced in fastify https://github.com/fastify/fastify/releases/tag/v4.23.0
=> fix: Removed deprecated properties usage in Fastify instrumentation

plugins/node/opentelemetry-instrumentation-redis-4/src/instrumentation.ts
This fixes the "no original function multi to wrap" warning from shimmer when wrapping recent versions of `@redis/client`.
Refs: #1708
=> fix(instrumentation-redis-4): avoid shimmer warning by only wrapping multi/MULTI if they exist

plugins/node/opentelemetry-instrumentation-redis-4/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-redis-4/test/redis.test.ts
The instrumentation was not handling a rejection of the promise from client.multi(), resulting in unended spans and an unhandleRejection event.
Fixes: #1708
---
This is based on work by @FredrikAugust in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1717.
=> fix(instrumentation-redis-4): fix unhandledRejection in client.multi(...) handling

plugins/node/opentelemetry-instrumentation-fastify/src/constants.ts, plugins/node/opentelemetry-instrumentation-fastify/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-fastify/test/instrumentation.test.ts
Fixes: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1762
This changes to an allow-list of hook names to wrap -- which means that if a new hook is added, then we won't create spans for it, but we also won't accidentally crash. :)
=> fix(instrumentation-fastify): do not wrap preClose and onRequestAbort hooks

plugins/node/opentelemetry-instrumentation-mongodb/src/instrumentation.ts
- Previous fix for `mongodb` instrumentation was using `AsynResource.bind` API which has different behaviour in different node versions. This leads to the instrumentation breaking `mongodb` driver for node v14
- make use of `context.bind` from `@opentelemetry/api` which is not affected by different node versions and is the recommended way to do it (thanks for the tip @Flarna)
Closes: #1759
=> fix: use context API to bind connection checkOut callback

plugins/node/opentelemetry-instrumentation-fastify/package.json, plugins/node/opentelemetry-instrumentation-mysql/examples/package.json
Experimental dependencies were pinnend in a way to not allow patch releases. This PR changes the pinned to a caret version that'll allow patch releases for experimental packages.
=> chore(deps): unpin @opentelemetry/* in fastify instrumentation and mysql example

plugins/node/opentelemetry-instrumentation-graphql/src/utils.ts, plugins/node/opentelemetry-instrumentation-graphql/test/graphql.test.ts, plugins/node/opentelemetry-instrumentation-graphql/test/helper.ts
Fixes #1791 
-
This PR updates (opentelemetry-instrumentation-graphql) the resolvers' span name. 
It will show something like: `graphql-resolve hello` instead of `graphql-resolve`. This is very useful to easily understand at a top level which field is being resolved.
E.g.,
```
query ExampleQuery {
me {
name 
}
}
```
=> chore(graphql): update span name to show the resolver name

package-lock.json
This PR was generated from running `npm install --package-lock-only`. It undoes part of the change by renovate in #1723.
See discussion at https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1806
=> chore: sync package-lock file to package.json files

package-lock.json, plugins/node/opentelemetry-instrumentation-mysql2/package.json
Types are included in 'mysql2' now (as of some 2.x release).
The github:types/mysql2 dependency is problematic for dependabot version updates.
See: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1806#issuecomment-1816889209
=> chore(instrumentation-mysql2): drop unneed @types/mysql2 dep

.github/workflows/release-please.yml
- see #1798, release-please is not updating package-lock.json with the new versions, so currently we'd need to do this manually - however release please force-pushes on each merge to main, so this is tedious.
- we currently do not use the opentelemetrybot account to create release PRs
- [link to community repo issue to get the required access to @opentelemetrybot](https://github.com/open-telemetry/community/issues/1814)
- uses opentelemetrybot credentials to create release PRs via release please
- adds a commit as opentelemetrybot, which syncs the package-lock.json (@opentelemetrybot has signed the CLA)
=> fix(ci): use opentelemetrybot to sync package-lock.json on release PRs

plugins/node/opentelemetry-instrumentation-net/src/instrumentation.ts
=> fix(instrumentation-net): Don't operate on closed span

plugins/web/opentelemetry-instrumentation-user-interaction/README.md
Documents config options for this instrumentation.
Closes #1770
- Add README docs for `eventNames` option
- Add README docs for `shouldPreventSpanCreation` option
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206095275723756
=> docs(user-interaction): update docs to include examples of config options

plugins/node/opentelemetry-instrumentation-redis-4/.tav.yml
redis@4.6.9 was a bad release that accidentally broken v14 support. This updates the versions test to skip that release, and also reduces the number of versions tested from 27 to 8 by selecting just the current latest minor releases.
Also, drop the pretest config that (a) was never used because of the wrong indentation and (b) is no longer valid since the move to npm workspaces.
Refs: #1860
---
**Note**: The redis-4 TAV tests still fail with Node v18 and v16 (sometimes, I think). That is a separate issue to what this one is fixing.
=> test: fix redis-4 TAV tests with Node.js v14

plugins/node/opentelemetry-instrumentation-redis-4/test/redis.test.ts
The beforeEach() hook was not awaited, so afterEach() could run before it completed, resulting in a client.disconnect() that rejects, and a mocha hook that calls done() twice.
Refs: #1860
The redis-4 tests are *sometimes* failing as follows. There is a timing race in the test.
```
1) redis@^4.0.0
"after each" hook in "redis@^4.0.0":
Error: done() called multiple times in hook <redis@^4.0.0 "after each" hook> of file /Users/trentm/tm/opentelemetry-js-contrib2/plugins/node/opentelemetry-instrumentation-redis-4/test/redis.test.ts; in addition, done() received error: TypeError: Cannot read properties of undefined (reading 'destroy')
...
```
With this patch to add some debug prints:
```diff
diff --git a/plugins/node/opentelemetry-instrumentation-redis-4/test/redis.test.ts …
```
=> test: fix race in redis-4 tests

package-lock.json, packages/opentelemetry-host-metrics/package.json
…n vulnerability in systeminformation
In the current version of the systeminformation library used by the host metrics package, a pretty serious vulnerability exists. That being the arbitrary command injection. This pull request addresss that by bumping the version of the library.
-
This changes is only comprised of a version bump.
-
=> fix(host-metrics): bump minimum systeminformation version to 5.21.20 (security)

.github/workflows/test-all-versions.yml, .github/workflows/unit-test.yml
This is as a workaround for ESM testing failing with v18.19.0 due
to node's off-thread ESM loading and import-in-the-middle's limitation
with reexports.
Refs: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1872
=> test: temporarily pin Node.js 18 testing to 18.18.2

GUIDELINES.md
This PR showcases the use of [generic types]((https://www.typescriptlang.org/docs/handbook/2/generics.html#generic-types)) when exporting types to the public API that depend on the instrumented package.
The generic types approach seeks to avoid adding a types package as a dependency of the instrumentation because it may bring some problems to consumers like https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1787
This approach has been added as a replacement of the `any` type approach since its the fallback type when using a generic
- update guildelines doc
cc: @blumamir
=> chore: update guidelines

detectors/node/opentelemetry-resource-detector-azure/src/detectors/AzureAppServiceDetector.ts, detectors/node/opentelemetry-resource-detector-azure/test/detectors/AzureAppServiceDetector.test.ts, detectors/node/opentelemetry-resource-detector-azure/test/detectors/AzureFunctionsDetector.test.ts
When running inside of an Azure Function and in the case where both the Azure Functions and Azure App Services detector were being run in the same application, because the Azure App Service check was not exclusive of the Azure Functions check, the application would incorrectly be identified as running inside of Azure App Services.
This PR also adds tests for both Azure Functions and Azure App Services detectors to ensure that they function as expected when running in the same application.
=> fix: Fix Azure Fns Detector When Running with App Service Detector

plugins/node/instrumentation-perf-hooks/package.json
Having a prepare script in the monorepo means that it runs during 'npm ci' which can break if some needed deps for that script haven't yet been installed.
This is the same change that was part of https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1771
From that PR's description:
> s/prepare/prepublishOnly/g is to avoid running the compile step in packages before npm install for all packages has completed. It resulted in various build errors. Using prepublishOnly is recommended (https://docs.npmjs.com/cli/v10/using-npm/scripts#prepare-and-prepublish) and is what the core repo was already doing.
I hit a breakage in `npm ci` in a separate PR (https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1938). A few of the checks started failing:
E.g.: …
=> fix(instr-perf-hooks): avoid 'prepare' npm script because that runs on 'npm install'

plugins/node/instrumentation-perf-hooks/test/event_loop_utilization.test.ts
This is to give more detail if those asserts fail. I suspect the
'val < 1' test is flaky.
Refs: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1960
=> chore(instr-perf-tools): add debugging output to some test asserts

plugins/node/opentelemetry-instrumentation-graphql/README.md
- Fix outdated documentation about supported graphql deps versions
- README update supported versions by the instrumentation (PR https://github.com/open-telemetry/opentelemetry-js-contrib/pull/998 should allow to also use GQL version 16, but doc still mentioned only <16).
=> docs(instrumentation-graphql): gql supported versions

detectors/node/opentelemetry-resource-detector-azure/package.json
Although @opentelemetry/api is in devDependencies, @opentelemetry/api is missing in @opentelemetry/resource-detector-azure's peerDependencies. This cause failures in strict installation layout for some package managers. 
Add @opentelemetry/api as peerDependencies in @opentelemetry/resource-detector-azure
=> fix: Add @opentelemetry/api as peerDependencies in @opentelemetry/resource-detector-azure

plugins/node/instrumentation-runtime-node/README.md, plugins/node/instrumentation-runtime-node/src/index.ts, plugins/node/instrumentation-runtime-node/src/instrumentation.ts, plugins/node/instrumentation-runtime-node/src/types.ts, plugins/node/instrumentation-runtime-node/test/event_loop_utilization.test.ts
See https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1970#issuecomment-1974965699
=> fix(instrumentaiton-runtime-node)!: rename exported instrumentation to match package name

package-lock.json, plugins/node/instrumentation-runtime-node/package.json
- reduce 'mocha' dep to v7 used by all other packages
- bump /api peer dep to 1.3.0 (the version when api-metrics was merged into api)
* * *
This replaces https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1967. Because this package has moved to a new name (used to be instrumentation-perf-tools), it was easier to start with a fresh PR. This also takes into consideration Marc's feedback at https://github.com/open-telemetry/opentelemetry-js-contrib/pull/1967#issuecomment-1968578311
=> chore(instr-runtime-node): update some deps to same versions as other contrib packages

plugins/node/opentelemetry-instrumentation-mongodb/.tav.yml
Since the move to npm workspaces in #1771 this pretest step is
no longer needed for TAV test runs.
* * *
I had removed most `pretest: ...` entries from .tav.yml files in #1771, but I missed a couple.
=> chore(instr-mongodb): drop obsolete 'pretest' step from TAV run

plugins/node/opentelemetry-instrumentation-aws-sdk/src/services/sqs.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/test/sqs.test.ts
=> fix(instr-aws-sdk): ensure that instrumentation does not crash on bogus SQS.sendMessageBatch input

metapackages/auto-instrumentations-node/README.md
- The link to the HTTP instrumentation package is broken
- Updated with the correct URL
=> docs(auto-instrumentations-node): fix link to HTTP instrumentation

package-lock.json, plugins/node/opentelemetry-instrumentation-express/README.md, plugins/node/opentelemetry-instrumentation-express/package.json, plugins/node/opentelemetry-instrumentation-express/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-express/test/custom-config.test.ts, plugins/node/opentelemetry-instrumentation-express/test/express.test.ts, plugins/node/opentelemetry-instrumentation-express/test/hooks.test.ts
- updates #2025 
In express instrumentation package:
- Update `@opentelemetry/semantic-conventions` to `^1.22`
- Replace `SemanticAttributes.HTTP_ROUTE` with exported string `SEMATTRS_HTTP_ROUTE`
- Update `README` with new semantic convention package version and key
=> chore(instr-express): use exported strings for attributes

plugins/node/opentelemetry-instrumentation-pg/src/enums/SpanNames.ts, plugins/node/opentelemetry-instrumentation-pg/src/index.ts, plugins/node/opentelemetry-instrumentation-pg/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-pg/src/utils.ts
The amount of allocations that opentelemetry produces is too high
Replaced attributes passed on span creation with span.setAttirbutes to avoid multiple remapping inside startSpan function, reused kind by providing constant and replaced string interpolation with constants
=> perf(instrumentation-pg): reduce temp objects allocations

plugins/node/instrumentation-runtime-node/src/instrumentation.ts
The constructor of the instrumentation runtime node does not mixin the default config. This means that if I pass an empty object, the `eventLoopUtilizationMeasurementInterval` will be undefined, which has the side-effect of the configured interval to be near 0.
Similarly to all other instrumentations, I've mixed in the default config to make sure default objects are always defined. Please note that the instrumentation file itself didn't have tests, so I haven't added any.
=> fix(instrumentation-runtime-node): mixin default config in constructor

CONTRIBUTING.md
- Closes #1986 ?
- update pr guidelines section 
- add development quickstart
- add more detail for general guidance
- add tools and dev header section
- update note about changelog
- update contributing toc
=> docs: Update contributing doc

detectors/node/opentelemetry-resource-detector-alibaba-cloud/README.md
- Update README of Alibaba resource detector to add a table with values getting detected.
=> chore: update readme for alibaba resource detector

detectors/node/opentelemetry-resource-detector-container/package.json, detectors/node/opentelemetry-resource-detector-container/src/detectors/ContainerDetector.ts, package-lock.json
On package `opentelemetry-resource-detector-container`:
- Update `@opentelemetry/semantic-conventions` from `^1.0.0` to `^1.22.0`
- Use exported strings for Semantic Resource Attributes.
=> chore(resource-detector-container): use exported strings for attributes

.github/component_owners.yml
Add `maryliag` as CODEOWNER of `plugins/node/opentelemetry-instrumentation-pg` as discussed on SIG meeting of March 27.
=> chore: add maryliag as CODEOWNER of opentelemetry-instrumentation-pg

package-lock.json, plugins/node/opentelemetry-instrumentation-koa/package.json, plugins/node/opentelemetry-instrumentation-koa/src/utils.ts, plugins/node/opentelemetry-instrumentation-koa/test/koa.test.ts
* Updates [Update usage of semantic conventions to new exported strings #2025](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2025)
In koa instrumentation package:
* Update `@opentelemetry/semantic-conventions` to `^1.22`
* Replace `SemanticAttributes.HTTP_ROUTE` with exported string `SEMATTRS_HTTP_ROUTE`
=> feat(koa): Use exported strings for attributes

detectors/node/opentelemetry-resource-detector-alibaba-cloud/package.json, detectors/node/opentelemetry-resource-detector-alibaba-cloud/src/detectors/AlibabaCloudEcsDetector.ts, detectors/node/opentelemetry-resource-detector-alibaba-cloud/test/detectors/AlibabaCloudEcsDetector.test.ts, package-lock.json
On package `opentelemetry-resource-detector-alibaba-cloud`:
- Update `@opentelemetry/semantic-conventions` from `^1.0.0` to `^1.22.0`
- Use exported strings for Semantic Resource Attributes, Cloud Platform Values and Cloud Provider Values.
=> chore(resource-detector-alibaba): use exported strings for attributes

package-lock.json, plugins/node/opentelemetry-instrumentation-pg/package.json, plugins/node/opentelemetry-instrumentation-pg/src/utils.ts, plugins/node/opentelemetry-instrumentation-pg/test/pg-pool.test.ts, plugins/node/opentelemetry-instrumentation-pg/test/pg.test.ts, plugins/node/opentelemetry-instrumentation-pg/test/utils.test.ts
On package `opentelemetry-instrumentation-pg`:
- Update `@opentelemetry/semantic-conventions` from `^1.0.0` to `^1.22.0`
- Use exported strings for Semantic Attributes
=> chore(opentelemetry-instrumentation-pg): use exported strings 

detectors/node/opentelemetry-resource-detector-aws/package.json, detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsBeanstalkDetector.ts, detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEc2Detector.ts, detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEcsDetector.ts, detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEksDetector.ts, detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsLambdaDetector.ts, detectors/node/opentelemetry-resource-detector-aws/test/detectors/AwsBeanstalkDetector.test.ts, detectors/node/opentelemetry-resource-detector-aws/test/detectors/AwsEcsDetector.test.ts, package-lock.json
On package `opentelemetry-resource-detector-aws`:
- Update `@opentelemetry/semantic-conventions` from `^1.0.0` to `^1.22.0`
- Use exported strings for Semantic Resource Attributes, Cloud Platform Values and Cloud Provider Values.
=> chore(resource-detector-aws): use exported strings for attributes

detectors/node/opentelemetry-resource-detector-gcp/README.md
- Update README of GCP Resource Detector to clarify the source of the data and add semantic conventions
=> docs(resource-detector-gcp): update readme for gcp resource detector

package-lock.json, packages/opentelemetry-test-utils/README.md, packages/opentelemetry-test-utils/package.json, packages/opentelemetry-test-utils/src/instrumentations/index.ts, packages/opentelemetry-test-utils/src/resource-assertions.ts
- Update @opentelemetry/semantic-conventions from ^1.0.0 to ^1.22.0
- Use exported strings for Semantic Resource Attributes
=> chore(test-utils): update semantic resource attributes

detectors/node/opentelemetry-resource-detector-container/README.md
- Update README of Container Resource Detector to clarify the source of the data and add semantic conventions
=> docs(resource-detector-container): update readme for container resource detector

detectors/node/opentelemetry-resource-detector-aws/README.md
- Update README of AWS Resource Detector to clarify the source of the data and add Semantic Conventions.
=> docs(resource-detector-aws): update readme for aws resource detector

detectors/node/opentelemetry-resource-detector-instana/README.md
- Update README of Instana Resource Detector to clarify the source of the data and add Semantic Conventions
=> docs(resource-detector-instana): update readme for instana resource detector

.github/component-label-map.yml, package-lock.json, plugins/node/instrumentation-undici/.tav.yml, plugins/node/instrumentation-undici/README.md, plugins/node/instrumentation-undici/package.json, plugins/node/instrumentation-undici/src/undici.ts, plugins/node/instrumentation-undici/test/undici.test.ts
- 'codecov' npm script was copypasta from core repo
- update to same test-all-versions ver as other pkgs in the workspace
- update undici to latest (it is a security update)
- add label-prs workflow support pkg:instrumentation-undici
- reduce number of versions tested with TAV
- skip a particular failing test case for very old undici versions
* * *
I also added the pkg: label for this instr: https://github.com/open-telemetry/opentelemetry-js-contrib/labels?q=undici
=> chore(instr-undici): updates/tweaks for new undici instrumentation

package-lock.json, plugins/node/instrumentation-amqplib/README.md, plugins/node/instrumentation-amqplib/package.json, plugins/node/instrumentation-amqplib/src/amqplib.ts, plugins/node/instrumentation-amqplib/src/utils.ts
- Replace `SemanticAttributes.*` with exported strings `SEMATTRS_*`
=> refactor(instr-amqplib): use exported strings for attributes

package-lock.json, plugins/node/opentelemetry-instrumentation-router/README.md, plugins/node/opentelemetry-instrumentation-router/package.json, plugins/node/opentelemetry-instrumentation-router/src/instrumentation.ts
- Replace `SemanticAttributes.HTTP_ROUTE` with exported string `SEMATTRS_HTTP_ROUTE`
=> refactor(instr-router): use exported strings for attributes

package-lock.json, plugins/node/instrumentation-mongoose/README.md, plugins/node/instrumentation-mongoose/package.json, plugins/node/instrumentation-mongoose/src/mongoose.ts, plugins/node/instrumentation-mongoose/src/utils.ts, plugins/node/instrumentation-mongoose/test/asserts.ts, plugins/node/instrumentation-mongoose/test/mongoose.test.ts
- Replace `SemanticAttributes.*` with exported strings `SEMATTRS_*`
=> refactor(instr-mongoose): use exported strings for attributes

package-lock.json, plugins/node/opentelemetry-instrumentation-restify/README.md, plugins/node/opentelemetry-instrumentation-restify/package.json, plugins/node/opentelemetry-instrumentation-restify/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-restify/test/restify.test.ts
- Replace `SemanticAttributes.HTTP_ROUTE` with exported string `SEMATTRS_HTTP_ROUTE`
=> refactor(instr-restify): use exported strings for attributes

plugins/node/instrumentation-undici/test/undici.test.ts
Test all versions (TAV) tests were failing with Node.js 14 and 16
because of subtle behaviour changes in socket end handling in
Node.js and undici for a test that tries a bogus request. This
restores earlier work-around code mistakenly removed in #2085.
* * *
Since #2085, TAV tests for Node.js 14 and 16 started failing. E.g.: https://github.com/open-telemetry/opentelemetry-js-contrib/actions/runs/8724672054/job/23935801386
```
> @opentelemetry/instrumentation-undici@0.1.0 test-all-versions
> tav
-- required packages ["undici@5.28.4"]
-- installing ["undici@5.28.4"]
-- running test "npm run test" with undici (env: {})
> @opentelemetry/instrumentation-undici@0.1.0 test
> nyc ts-mocha -p tsconfig.json test/**/*.test.ts
...
UndiciInstrumentation `undici` tests
disable()
✓ should not create …
```
=> test(instr-undici): fix TAV failures with Node.js 14 and 16

package-lock.json, plugins/node/opentelemetry-instrumentation-mysql2/README.md, plugins/node/opentelemetry-instrumentation-mysql2/package.json, plugins/node/opentelemetry-instrumentation-mysql2/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-mysql2/src/utils.ts, plugins/node/opentelemetry-instrumentation-mysql2/test/mysql.test.ts
- Replace `SemanticAttributes.*` with exported strings `SEMATTRS_*`
=> refactor(instr-mysql2): use exported strings for attributes

package-lock.json, plugins/node/instrumentation-fs/package.json
- updates #2025 
- sort of
- remove unused package `@opentelemetry/semantic-conventions`
=> chore(instrumentation-fs): remove unused semconv package

plugins/node/instrumentation-undici/README.md, plugins/node/opentelemetry-instrumentation-express/README.md, plugins/node/opentelemetry-instrumentation-fastify/README.md, plugins/node/opentelemetry-instrumentation-redis/README.md, plugins/web/opentelemetry-instrumentation-document-load/README.md
A key column was added to several READMEs, but it was decided to not have them anymore.
So this commit removes the column from the doc that were already added.
=> docs: remove `key` column on readme

examples/web/examples/document-load/index.js, examples/web/examples/meta/index.js, examples/web/examples/user-interaction/index.js, examples/web/package.json
On package `examples/web`:
- Update `@opentelemetry/semantic-conventions` `^1.23.0`
- Use exported strings for Semantic Attributes.
=> chore(examples/web): use exported strings for attributes

package-lock.json, plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-aws-lambda/test/integrations/lambda-handler.test.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/README.md, plugins/node/opentelemetry-instrumentation-aws-sdk/package.json, plugins/node/opentelemetry-instrumentation-aws-sdk/src/aws-sdk.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/src/services/dynamodb.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/src/services/lambda.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/src/services/sns.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/src/services/sqs.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/src/utils.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/test/aws-sdk-v2.test.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/test/aws-sdk-v3.test.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/test/dynamodb.test.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/test/lambda.test.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/test/sns.test.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/test/sqs.test.ts
- updates #2025 
- Update `@opentelemetry/semantic-conventions` to `^1.22` for aws-sdk instrumentation
- Replace `SemanticAttributes.*` with exported strings `SEMATTRS_*`
- Replace `SemanticResourceAttributes.*` with exported strings `SEMRESATTRS_*`
- Replace `DbSystemValues.*` with exported strings `DBSYSTEMVALUES_*`
- Replace `MessagingDestinationKindValues.*` with exported strings `MESSAGINGDESTINATIONKINDVALUES_*`
- Replace `MessagingOperationValues.*` with exported strings `MESSAGINGOPERATIONVALUES_*`
- Replace deprecated `SpanAttributes` with `Attributes`
=> refactor(instr-aws-sdk): use exported strings for attributes

plugins/web/opentelemetry-instrumentation-document-load/test/documentLoad.test.ts
The change in https://github.com/open-telemetry/opentelemetry-js/pull/4486
means that a addSpanNetworkEvent() in  v1.24.0 and
later might get dropped -- if its time value is before the fetchStart time.
Typically this happens if the event time value is 0.
=> test(instr-document-load): fix test to allow missing network span events

.github/workflows/release-please.yml
rolls back #2133 as the release workflow is now not working anymore (step output does not work correctly)?
Reopens #2020
=> fix(ci): rollback #2133

.github/workflows/release-please.yml
- closes #2020
- Add conditional checks to steps that require a release to be created first.
According to [`release-please-action` Outputs section](https://github.com/google-github-actions/release-please-action?tab=readme-ov-file#outputs) `releases_created` is `true` if any release was created, `false` otherwise. This should be the right option compared to the previous attempt that used `release_created` which is only `true` if a root component release was created, `false` otherwise. Thanks for the [tip](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2020#issuecomment-2078830357) @pichlermarc ! Hopefully this one works better. 🤞
=> ci: only publish after releases are created

metapackages/auto-instrumentations-web/tsconfig.esm.json, metapackages/auto-instrumentations-web/tsconfig.esnext.json, metapackages/auto-instrumentations-web/tsconfig.json, plugins/node/instrumentation-cucumber/tsconfig.json, plugins/node/instrumentation-mongoose/tsconfig.json, plugins/node/opentelemetry-instrumentation-mongodb/tsconfig.json, plugins/web/opentelemetry-instrumentation-user-interaction/tsconfig.esm.json, plugins/web/opentelemetry-instrumentation-user-interaction/tsconfig.esnext.json, plugins/web/opentelemetry-instrumentation-user-interaction/tsconfig.json
`skipLibCheck: true` is set a few instrumentation libraries, even though they're not necessary anymore. The only remaining instrumentation that needs it is `@opentelemetry/instrumentation-lru-memoizer`.
=> chore: remove skipLibCheck: true from tsconfigs where it is not necessary

plugins/node/opentelemetry-instrumentation-pino/test/pino-enabled.test.ts
- updates #1942 
- add back test for ESM support in pino instrumentation, which was inadvertently dropped in a separate PR
=> test(instrumentation-pino): add test for ESM

packages/baggage-span-processor/README.md
Fixes the NPM links in the Baggage Span Processor README.
- Update the img and url links in README
=> docs: Fix baggage span processor NPM links

.github/workflows/test-all-versions.yml, .github/workflows/unit-test.yml, package-lock.json
- Updates to 1.24.1/0.51.1. Due to the used dependency ranges, this updates `package-lock.json` only.
- Also removes the workaround that pinned tests to use 18.18.2
Closes #2021 
Partially enables #2169
=> chore: update otel and unpin node 18 in tests

plugins/node/opentelemetry-instrumentation-connect/package.json
Missing source-maps in instrumentation-connect.
Fixes #2199
- adds source-map files to `files`
=> fix(instrumentation-connect): add source maps to package

.github/component_owners.yml
I noticed that a number of the dirs in `component_owners.yml` were incorrect.
```sh
% cat .github/component_owners.yml | rg '^  \w' | cut -d: -f1 | while read d; do if [[ ! -d $d ]]; then echo bad dir $d; fi; done
bad dir packages/opentelemetry-sampler-aws-xray
bad dir plugins/node/opentelemetry-instrumentation-runtime-node
bad dir plugins/node/opentelemetry-instrumentation-undici
bad dir propagators/opentelemetry-propagator-grpc-census-binary
```
=> chore: fix some package dirs in component_owners metadata

detectors/node/opentelemetry-resource-detector-container/package.json, plugins/node/instrumentation-amqplib/package.json, plugins/node/instrumentation-fs/package.json, plugins/node/instrumentation-lru-memoizer/package.json, plugins/node/instrumentation-mongoose/package.json, plugins/node/instrumentation-socket.io/package.json, plugins/web/opentelemetry-instrumentation-document-load/package.json, plugins/web/opentelemetry-instrumentation-long-task/package.json, plugins/web/opentelemetry-instrumentation-user-interaction/package.json, plugins/web/opentelemetry-plugin-react-load/package.json
Few packages had this content in `package.json` scripts:
```json
"compile": "npm run version:update && tsc -p .",
"precompile": "tsc --version && lerna run version:update --scope @opentelemetry/foo --include-dependencies",
```
Since running the `versions:update` script is already part of the `"precompile"` script, there is no need to run it again in the compile. most packages in this repo are already written this way, and this PR aligns the remaining ones
=> chore: remove duplicate "version update" in compile script 

package-lock.json, plugins/node/instrumentation-undici/package.json
remove unused dev dependenc on "superagent" in `@opentelemetry/instrumentation-undici`. See https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2175#discussion_r1591121093
=> chore(undici): remove unused dev dep on superagent

plugins/node/opentelemetry-instrumentation-pino/test/pino-enabled.test.ts
The ESM tests are out of process so the setup done in
setupInstrumentationAndInitTestContext() isn't relevant.
=> test: minor cleanup to pino ESM test

plugins/node/opentelemetry-instrumentation-pg/README.md
The PR https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2171 removed the postgres example, but there was still a link to the file on the README file, which was now returning 404.
This PR remove the mention to the no longer existing file
=> chore: remove link to non existing file

plugins/node/instrumentation-undici/package.json
- URL currently points to invalid git location
- Fix Undici homepage url in package.json
=> chore(undici): Fix homepage url

packages/baggage-span-processor/package.json
Fixes the following error:
```
Error: Cannot find module '/Users/long/Repos/wise-rock/node_modules/@opentelemetry/baggage-span-processor/build/src/index.ts'. Please verify that the package.json has a valid "main" entry
at tryPackage (node:internal/modules/cjs/loader:415:19)
at Function.Module._findPath (node:internal/modules/cjs/loader:665:18)
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1034:27)
at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (/Users/long/Repos/wise-rock/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
at Function.Module._resolveFilename (/Users/long/Repos/wise-rock/node_modules/tsconfig-paths/src/register.ts:115:36)
at Function.Module._load (node:internal/modules/cjs/loader:901:27) …
```
=> fix(baggage-span-processor): cannot find module

plugins/node/instrumentation-undici/README.md
Current options table points to https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-undici
Change to https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/instrumentation-undici and fix how line numbers are referenced
=> docs(undici): Update option links to point to right link

plugins/node/instrumentation-undici/src/undici.ts, plugins/node/instrumentation-undici/test/undici.test.ts
- undici instrumentation wrongly reports the first header's name as the `user-agent` if no `user-agent` header was set (default behavior of `undici` from what I can tell)
`request.headers.findIndex(h => h.toLowerCase() === 'user-agent')` returns `-1` if no `user-agent` header was present.
I added a check to avoid reporting `headers[0]` as `user-agent`
Added a test, not sure if it's useful? Especially as it might break in the future if `undici` decide to add a default `user-agent`
=> fix(instr-undici): wrong user agent reported if no user agent were set

plugins/node/instrumentation-dataloader/src/index.ts, plugins/node/instrumentation-fs/src/index.ts, plugins/node/instrumentation-fs/src/instrumentation.ts, plugins/node/instrumentation-fs/test/fs.test.ts, plugins/node/instrumentation-fs/test/fsHooks.test.ts, plugins/node/instrumentation-fs/test/fsPromises.test.ts, plugins/node/instrumentation-fs/test/fsPromisesHooks.test.ts, plugins/node/instrumentation-fs/test/parent.test.ts, plugins/node/instrumentation-lru-memoizer/src/index.ts, plugins/node/instrumentation-lru-memoizer/src/instrumentation.ts, plugins/node/instrumentation-lru-memoizer/test/index.test.ts, plugins/node/instrumentation-runtime-node/src/index.ts, plugins/node/instrumentation-tedious/src/index.ts, plugins/node/instrumentation-undici/src/index.ts, plugins/node/opentelemetry-instrumentation-generic-pool/src/index.ts, plugins/node/opentelemetry-instrumentation-generic-pool/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-generic-pool/test/index.test.ts, plugins/node/opentelemetry-instrumentation-knex/src/index.ts, plugins/node/opentelemetry-instrumentation-knex/test/index.test.ts, plugins/node/opentelemetry-instrumentation-memcached/src/index.ts, plugins/node/opentelemetry-instrumentation-memcached/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-memcached/test/index.test.ts, plugins/node/opentelemetry-instrumentation-mysql2/src/index.ts, plugins/node/opentelemetry-instrumentation-nestjs-core/src/index.ts, plugins/node/opentelemetry-instrumentation-nestjs-core/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-restify/src/index.ts, plugins/node/opentelemetry-instrumentation-restify/test/restify.test.ts, plugins/node/opentelemetry-instrumentation-router/src/index.ts, plugins/node/opentelemetry-instrumentation-router/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-router/test/index.test.ts
This PR is targets how we name and export instrumentation classes from our packages across the repo, and introduces consistency and best practices to align the code base.
It makes it so that:
- each instrumentation class has the same name as the name it is exported with (few were called `Instrumentation` instead of `FooInstrumentation`)
- align the `index.ts` file to export consistently - everything from `instrumentation.ts` and `type.ts`. This is to remove complexity and promote safe practices. This aligns the few places which were too complex, to an equivalent import and export statements to align with most packages in the repo.
- Remove the default export of the instrumentation class from the few places where it was present. since all instrumentations supports named exports of the …
=> fix!: export instrumentations only as named export

packages/opentelemetry-host-metrics/README.md, packages/opentelemetry-host-metrics/src/BaseMetrics.ts, packages/opentelemetry-host-metrics/test/metric.test.ts
Fixes https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2274
- Fields of `MetricsCollectorConfig` should all be optional.
- Remove unused option fields.
=> fix(host-metrics): make host metrics constructor options optional

package-lock.json, plugins/node/opentelemetry-instrumentation-koa/README.md, plugins/node/opentelemetry-instrumentation-koa/package.json, plugins/node/opentelemetry-instrumentation-koa/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-koa/src/internal-types.ts, plugins/node/opentelemetry-instrumentation-koa/src/types.ts, plugins/node/opentelemetry-instrumentation-koa/src/utils.ts, plugins/node/opentelemetry-instrumentation-koa/test/koa.test.ts
fixes #2228 
This PR aims to remove the instrumentation package dependency on the koa types packages, by making the relevant types generic and defaulting to `any`. That allows users who choose to implement the hook, to either use type `any`, or install the relevant types packages and populate the generic parameters.
**Breaking Change** 
- this PR makes it so that `KoaContext` is no longer exported as public type from the package 
- some hook info properties type will change to `any` by default, which should not break anyone I believe, but will no not verified  this variable typing as before.
**Prior Art**
defaults to any and allow to use generics to type correctly:
- [express instrumentation](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-in …
=> fix(koa)!: use generic config hook types and move dep to dev

plugins/node/opentelemetry-instrumentation-winston/src/instrumentation.ts
Fixes #2244
Removed error details in diag.warn call
=> fix(@opentelemetry/instrumentation-winston): Removing error details when @opentelemetry/winston-transport is not available

package-lock.json, plugins/web/opentelemetry-plugin-react-load/package.json
Updates `package-lock.json` to pull in updated OTel deps.
=> chore: update all otel deps

.github/component-label-map.yml, .github/component_owners.yml
I reached out to @rauno56 and he let me know that he's not actively working on OTel and the components in this repository anymore. 
This PR updates the component ownership/auto-labelling files accordingly.
=> chore: mark @rauno56 components as unmaintained

.github/workflows/release-please.yml
npm has a feature to display provenance statements for published packages. This allows users to see and verify how the package in npm has been built and published. Documentation for the npm feature is [here](https://docs.npmjs.com/generating-provenance-statements).
Since this repository is already using a Github Actions workflow to publish to npm, the only change is to add the `id-token` permission and configure npm to publish with provenance. There are three options documented [here](https://docs.npmjs.com/generating-provenance-statements#using-third-party-package-publishing-tools):
- `NPM_CONFIG_PROVENANCE` env variable
- `publishConfig.provenance` configuration in package.json
- flag in .npmrc file
I have chosen the environment variable. The package.json option would require updating …
=> ci: generate npm provenance statements when publishing

.github/workflows/close-stale.yml
See #2275, the `stale` label was applied and the bot commented even though it's a release PR (changes to unmaintained packages were part of that). 
This PR addresses two issues:
- To prevent `release-please` and `renovate-bot` from running into the 14-day autoclose for unmaintained packages this PR adds the labels `dependencies` and `autorelease:pending` to the exempt labels.
- To avoid misunderstandings, use `pkg-status:unmaintained:autoclose-scheduled` label instead of `stale`
=> chore: exempt dependencies, autorelease PRs from unmaintained-package autoclose

packages/opentelemetry-test-utils/README.md
- confusion about what package to install from npm
- Looks like this was renamed from test-utils to contrib-test-utils a few years back but the readme still uses the old name. I happened across it when I was looking for the test code and was confused about the package name. This is super tiny, merge at will.
=> docs(test-utils): fix package name in readme

plugins/node/opentelemetry-instrumentation-aws-sdk/src/aws-sdk.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/test/aws-sdk-v3.test.ts
Fixes https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2343
- Upon AWS SDK (v3) Client exceptions, AWS SDK V3 Span will not record http.status.code attribute into the span.
- For comparison, AWS SDK V2 Span already does record and [expects this attribute](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-aws-sdk/test/aws-sdk-v2.test.ts#L301-L303).
- Record `http.status.code` attribute into the span upon client exceptions for AWS SDK V3 Spans.
- Updated Unit Tests to check for `http.status.code` attribute
=> fix(aws-sdk): add http status code attribute to aws sdk span if aws sdk v3 client exception occurs

packages/opentelemetry-test-utils/src/test-utils.ts
Creation of a TestMetricReader that can be used during tests involving metric collection.
Created based on comment: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2349#discussion_r1708887639
For usage, the function `initMeterProvider` can be called on the `beforeEach` of tests, and the return of `metricReader` can be used such as `const { resourceMetrics, errors } = await metricReader.collect();`
Once a new version of the package `opentelemetry-test-utils` is created, I will update the PR mentioned above with its usage.
=> feat(opentelemetry-test-utils): create TestMetricReader

packages/opentelemetry-test-utils/src/test-utils.ts
Follow up from https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2388. I forgot to add the `export` to the new class `TestMetricReader` on that PR.
=> feat(opentelemetry-test-utils): export class TestMetricReader

plugins/node/instrumentation-undici/src/undici.ts, plugins/node/instrumentation-undici/test/fetch.test.ts, plugins/node/instrumentation-undici/test/metrics.test.ts, plugins/node/instrumentation-undici/test/undici.test.ts
Fixes: #2391 
- removed `enabled` internal config from the logic of the instrumentation. Now it relies only in enable/disable methods
- updated tests
=> fix(instr-undici): fix issue with config in constructor

plugins/node/instrumentation-tedious/.tav.yml, plugins/node/instrumentation-tedious/README.md, plugins/node/instrumentation-tedious/src/instrumentation.ts, plugins/node/instrumentation-tedious/test/instrumentation.test.ts
https://github.com/tediousjs/tedious/releases/tag/v19.0.0
tedious@19 bumps the min supported Node.js to 18.17.0.
Refs: #2400
=> feat(instr-tedious): support tedious@19

detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEcsDetectorSync.ts, detectors/node/opentelemetry-resource-detector-aws/src/detectors/AwsEksDetectorSync.ts, detectors/node/opentelemetry-resource-detector-container/src/detectors/ContainerDetector.ts
- Fix #2268 
- change log from warn to debug when detector failed to detect
=> fix(detectors): reduce diag level on detectors failing to detect

plugins/node/opentelemetry-instrumentation-generic-pool/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-generic-pool/test/index.test.ts
- The current span name emitted from `@opentelemetry/instrumentation-generic-pool` is `generic-pool.aquire`, but it should be `generic-pool.acquire` instead. For instance, see this [PR](https://github.com/getsentry/sentry-javascript/pull/13465/files/4d7ddbf7704b35cdc1a52ca25014315a6f6e72f2#r1731640158).
- Span name changed to `generic-pool.acquire`
=> fix(instrumentation-generic-pool): update span name typo

metapackages/auto-instrumentations-node/src/register.ts, metapackages/auto-instrumentations-node/test/register.test.ts, metapackages/auto-instrumentations-node/test/test-app/app-server.js
Fixes https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2383
Adds a one-shot `beforeExit` hook to call `NodeSDK.shutdown()`. In the event of SIGTERM  and the process gracefully exiting, shutdown may be called twice. I believe the additional calls to `shutdown()` should no-op so that is not a concern but may make for spammy logs.
I updated the tests to capture the expected behavior
- Shutdown on SIGTERM
- Shutdown when exiting normally
=> fix(auto-instrumentations-node): shutdown the SDK when the process exits normally

packages/opentelemetry-test-utils/src/test-fixtures.ts, plugins/node/opentelemetry-instrumentation-express/test/express.test.ts
This is a follow-up on https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2408#discussion_r1735862915
to update one more usage of `SpanKind.*` to `testUtils.OtlpSpanKind.*`.
While testing this locally I also noticed that the instr-express tests
using runTestFixture are flaky. The issue is that `TestCollector#sortedSpans`
can get the span ordering wrong when spans start in the same millisecond
(the resolution of span.startTimeUnixNano). This happens with Express
middleware spans on a fast machine.  I've updated `sortedSpans` to
fallback to using span.parentSpanId to attempt to get more reliable
sorting.
=> test(instrumentation-express): update to use correct span kind enum; also fix test flakiness

metapackages/auto-configuration-propagators/src/utils.ts
- When supplying `OTEL_PROPAGATORS` via an env var, `baggage` is mistakenly mapped to to the `W3CTraceContextPropagator`
- properly map `baggage` to to the `W3CBaggagePropagator `
=> fix: auto-config of baggage propagator

detectors/node/opentelemetry-resource-detector-gcp/package.json, detectors/node/opentelemetry-resource-detector-gcp/src/detectors/GcpDetector.ts, detectors/node/opentelemetry-resource-detector-gcp/test/detectors/GcpDetectorIntegration.test.ts
- this detector performs some request to get metadata from GCP. We should suppress the tracing for these requests
ref: #2320 
- suppress tracing when resolving attributes
- add test
=> fix(detector-gcp): suppress internal tracing

detectors/node/opentelemetry-resource-detector-alibaba-cloud/package.json, detectors/node/opentelemetry-resource-detector-alibaba-cloud/src/detectors/AlibabaCloudEcsDetector.ts, detectors/node/opentelemetry-resource-detector-alibaba-cloud/test/detectors/AlibabaCloudEcsDetectorIntegration.test.ts
- this detector performs some request to get metadata from Alibaba cloud. We should suppress the tracing for these requests
ref: #2320
- suppress tracing when resolving attributes
- add test
=> fix(detector-alibaba): suppres internal tracing

packages/opentelemetry-host-metrics/src/BaseMetrics.ts
Instead of requiring the `MeterProvider` class implementation as exported by `@opentelemetry/sdk-metrics`, change to simply require the `MeterProvider` interface as exported by `@opentelemtry/api`. This makes `HostMetrics` easier to initialize with the meter provider returned by `metrics.getMeterProvider()`
Initializing the `HostMetrics` object with a `meterProvider` as returned by `metrics.getMeterProvider()` files a type check:
```typescript
import { metrics } from "@opentelemetry/api";
import { HostMetrics } from "@opentelemetry/host-metrics";
const hostMetrics = new HostMetrics({ meterProvider: metrics.getMeterProvider() }); // <-- fails with TS2739
```
The compile-time error is:
```
Type 'MeterProvider' is missing the following properties from type 'MeterProvider': _sharedState, …
```
=> fix(host-metrics): widen MeterProvider type restriction in BaseMetrics class

detectors/node/opentelemetry-resource-detector-container/src/detectors/ContainerDetector.ts, detectors/node/opentelemetry-resource-detector-container/test/ContainerDetectorIntegration.test.ts
- this detector performs some `fs` operatoins to get metadata. We should suppress the tracing for these requests
ref: #2320 
- suppress tracing when resolving attributes
- add test
=> fix(detector-container): suppress internal tracing

.github/workflows/test-all-versions.yml, .github/workflows/unit-test.yml, packages/opentelemetry-test-utils/src/test-utils.ts
Per https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables
SA_PASSWORD (without the prefix) is deprecated.
=> test: update mssql envvar to MSSQL_SA_PASSWORD

.github/component-label-map.yml, .github/component_owners.yml
I had initially picked up ownership for the fastify instrumentation package from a previously unknown owner to keep it alive for a bit longer in case we were to go ahead and remove unmaintained packages.
However, with all the other responsibilities that come with maintaining the JS SIGs two repositories (https://github.com/open-telemetry/opentelemetry-js-contrib, https://github.com/open-telemetry/opentelemetry-js), I don't have a lot of time to dedicate to this instrumentation as other things tend to be higher priority (handling releases, issues, fixing bugs in core components, general repo maintenance). As such, with me as an owner, the instrumentation is effectively unmaintained as I never find enough time to actually work on it. Therefore this PR removes me as an owner to bring more …
=> chore(instrumentation-fastify): mark instrumentation as unmaintained

plugins/node/opentelemetry-instrumentation-fastify/.tav.yml, plugins/node/opentelemetry-instrumentation-fastify/src/instrumentation.ts
Resolves: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2438
Related: https://github.com/getsentry/sentry-javascript/issues/13774
Enables instrumentation on Fastify versions 5.x.x
Looking at [Fastify's v5 migration guide](https://fastify.dev/docs/latest/Guides/Migration-Guide-V5/), the breaking changes of this major release are mainly about removing deprecated methods. Those related to this SDK already seem to be covered.
The current set of tests is passing as is.
The newly introduced support for [Diagnostic Channels](https://fastify.dev/docs/latest/Guides/Migration-Guide-V5/#diagnostic-channel-support) can be implemented with a follow-up PR if OTEL maintainers decide to do so.
=> feat(instrumentation-fastify): Enable Fastify v5

detectors/node/opentelemetry-resource-detector-container/package.json
- we've switched to the codecov action, this script is unused and the dependency has also been removed already
=> chore(detector-contrainer): remove orphan codecov script

detectors/node/opentelemetry-resource-detector-alibaba-cloud/package.json, detectors/node/opentelemetry-resource-detector-container/package.json, package-lock.json, plugins/node/opentelemetry-instrumentation-pg/package.json
See #2472, we're using `@opentelemetry/core` but don't have it listed as a dependency in some packages.
- adds the dependency to the packages where it's missing (identified through comparing https://github.com/open-telemetry/opentelemetry-js-contrib/compare/auto-instrumentations-node-v0.50.0...auto-instrumentations-node-v0.50.1)
- pins the `@opentelemetry/semantic-conventions` dependency for `@opentelemetry/instrumentation-pg`  as it's using the `incubating` entrypoint, which may break on minor bumps.
=> fix: add missing @opentelemetry/core dependency

plugins/node/opentelemetry-instrumentation-pg/test/pg-pool.test.ts
- Trying to solve the flakiness of the test
=> chore(instrumentation-pg): use done on test

plugins/node/instrumentation-socket.io/src/socket.io.ts, plugins/node/instrumentation-socket.io/test/socket.io.test.ts, plugins/node/instrumentation-socket.io/test/utils.ts
Socket io span names might contain high cardinality data. I'm removing roomId from span names so it doesn't.
Issue: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1937
- I refactored names so It follows messaging semconv,  it's "send ${namespace}" / "receive ${namespace}"  instead of `... receive`. 
One question about should it be "receive", I think we might need to change it to "process"?
Given:
> “Receive” spans SHOULD be created for operations of passing messages to the application when those operations are initiated by the application code (pull-based scenarios).
>“Process” spans SHOULD be created for operations of passing messages to the application when those operations are not initiated by the application code (push-based scenarios). Such “Process” span covers …
=> fix: change span names for socket-io

plugins/node/instrumentation-undici/src/types.ts
- Previously RequestType was accidentally assigned with UndiciResponse while the correct type is UndiciRequest
- `ResponseHookFunction<RequestType>` had incorrect type
- Use correct type `UndiciRequest` for `RequestType` instead of wrong type `UndiciResponse`
=> fix(instrumentation-undici): Fix RequestType

metapackages/auto-configuration-propagators/README.md
Following #2411 , the links in the `auto-configuration-propagators` README are now broken, this PR sets them to the new up-to-date location
=> chore: fix broken links for aws propgators

plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts
Currently, ESM based handlers with `.mjs` file extension are not taken care of by AWS Lambda instrumentation, but ESM based handlers are supported since long time (https://aws.amazon.com/tr/about-aws/whats-new/2022/01/aws-lambda-es-modules-top-level-await-node-js-14/).
For the fix, while handler file is being resolved, in addition to `.js` and `.cjs` file extensions, `.mjs` file extension is also checked.
This PR is the contrib counter part of the https://github.com/open-telemetry/opentelemetry-js/pull/5094
=> feat(instrumentation-aws-lambda): take care of ESM based (`.mjs`) handlers

plugins/node/instrumentation-dataloader/README.md, plugins/node/instrumentation-fs/README.md, plugins/web/opentelemetry-instrumentation-long-task/README.md, plugins/web/opentelemetry-instrumentation-user-interaction/README.md
- updates #1778 
- updates readme to include section for semantic convention for those readme that do not have semantic convention usage. 
- Following readme where updated:
1. plugins/node/instrumentation-dataloader/README.md
2. plugins/node/instrumentation-fs/README.md
3. plugins/web/opentelemetry-instrumentation-long-task/README.md
4. plugins/web/opentelemetry-instrumentation-user-interaction/README.md
=> docs(multiple): update readme for semantic convention

CONTRIBUTING.md
- The current link is broken https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md
- Fixes the broken link for contribution processes which were moved in https://github.com/open-telemetry/community/pull/2051
=> fix(docs): broken link for community contribution lifecycle and processes

plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-aws-sdk/src/services/sns.ts
- The [String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated.
- This PR replaces `String.prototype.substr()` with [String.prototype.substring()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring)
=> chore(aws): replace deprecated substr with substring

examples/redis/src/server.ts
- Fixes https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2545#discussion_r1853307864
- uses crypto.randomBytes to generate uuid as recommended by CodeQL
=> chore(examples/redis): use crypto.randomBytes to generate uuid

examples/express/src/tracer.ts
Minor refactor to clean up imports from the api pkg.
Remove the DiagConsoleLogger for now. There isn't any useful diag log output
for this example, and configuring it just adds some noise.
=> refactor(examples/express): small refactor of imports

package-lock.json, plugins/node/opentelemetry-instrumentation-koa/.tav.yml, plugins/node/opentelemetry-instrumentation-koa/package.json, plugins/node/opentelemetry-instrumentation-koa/test/koa.test.ts
Fixes: #2564 
- skip `@koa/router` tests if version is not compatible with nodejs version
=> chore(instr-koa): update instrumentation-koa tests

packages/opentelemetry-test-utils/src/test-fixtures.ts, plugins/node/opentelemetry-instrumentation-hapi/test/hapi.test.ts
- Assertion errors thrown inside `runTextFixture` are swallowed and not reported.
- Reject the `runTestFixture` promise with the thrown error, if there is one.
- Updated Hapi tests that seem to be silently failing before this update.
=> fix(test-utils): Don't swallow assertion errors from `checkResult` and `checkCollector`

plugins/node/opentelemetry-instrumentation-hapi/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-hapi/test/hapi-plugin.test.ts
https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2624
Correctly bind `this` to plugin's `register` method.
=> fix(instrumentation-hapi): fix this binding for plugin register method

plugins/node/opentelemetry-instrumentation-aws-sdk/.tav.yml
- Fixes: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2627
- Sets AWS SDK for JavaScript v3 versions based on Node.js version they support.
=> test(aws-sdk): set v3 versions based on Node.js support

detectors/node/opentelemetry-resource-detector-alibaba-cloud/package.json, detectors/node/opentelemetry-resource-detector-alibaba-cloud/tsconfig.esm.json, detectors/node/opentelemetry-resource-detector-aws/package.json, detectors/node/opentelemetry-resource-detector-aws/tsconfig.esm.json, detectors/node/opentelemetry-resource-detector-azure/package.json, detectors/node/opentelemetry-resource-detector-azure/tsconfig.esm.json, detectors/node/opentelemetry-resource-detector-container/package.json, detectors/node/opentelemetry-resource-detector-container/tsconfig.esm.json, detectors/node/opentelemetry-resource-detector-gcp/package.json, detectors/node/opentelemetry-resource-detector-gcp/tsconfig.esm.json, detectors/node/opentelemetry-resource-detector-github/package.json, detectors/node/opentelemetry-resource-detector-github/tsconfig.esm.json, detectors/node/opentelemetry-resource-detector-instana/package.json, detectors/node/opentelemetry-resource-detector-instana/tsconfig.esm.json
As OTEL FAAS SIG, we are working on reducing OTEL Lambda Nodejs layer coldstart overhead and bundling has the biggest impact. But bundling tools like webpack, esbuild don't like CJS modules while tree-shaking, but ESM modules. So, in this PR, we are configuring build process to generate ESM build files too.
To be able to generate ESM build files too, this PR is 
- introducing `tsconfig.esm.json` files
- and updating scripts accordingly in the `package.json`
- and defining ESM file paths in the `files` section of the `package.json` for their discoverability
=> feat(detectors): generate esm build files too

plugins/node/opentelemetry-instrumentation-aws-sdk/.tav.yml
Tests are failing on `main` - it seems that the rules for Node.js v14/v16 don't work as intended. This changes the `^` to `>=`. Should be equivalent since there's also an upper limit specified for each rule.
=> test(instrumentation-aws-sdk): adapt tav versions include rule for v14 and v16

plugins/node/opentelemetry-instrumentation-aws-sdk/src/services/sqs.ts
- Noticed in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2623
- Removes dependency on type from JS SDK v2 devDependency.
=> chore(aws-sdk): remove dependency on SQS type from JS SDK v2

plugins/node/opentelemetry-instrumentation-fastify/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-fastify/test/instrumentation.test.ts
This PR adds an additional export that is part of the fastify public API to the `InstrumentationNodeModuleDefinition` patch function. Without this patch, 
fastify v4.8+ exports an object named `errorCodes` as both a property of the default export and as a named export.
The export is documented at https://github.com/fastify/fastify/blob/4.x/docs/Reference/Errors.md?plain=1#L236.
This closes #2027.
=> fix(instrumentation-fastify): add missing module export

detectors/node/opentelemetry-resource-detector-alibaba-cloud/package.json, detectors/node/opentelemetry-resource-detector-aws/package.json, detectors/node/opentelemetry-resource-detector-azure/package.json, detectors/node/opentelemetry-resource-detector-container/package.json, detectors/node/opentelemetry-resource-detector-gcp/package.json, detectors/node/opentelemetry-resource-detector-github/package.json, detectors/node/opentelemetry-resource-detector-instana/package.json
In my previous [PR](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2636), I have forgotten to mark resource detector modules as side effect free. So, during my internal tests with custom built resource detector packages, I have noticed that they are not tree-shaked by webpack even though they are not referenced.
Add `sideEffects` property as `false` to the `package.json` files of all the resource detector modules.
=> feat(detectors): mark as side effect free

plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts, plugins/node/opentelemetry-instrumentation-aws-lambda/src/semconv.ts
Refs: https://github.com/open-telemetry/opentelemetry-js/tree/main/semantic-conventions#unstable-semconv
=> fix(instrumentation-aws-lambda): do not import from semantic-conventions incubating entry-point

metapackages/auto-instrumentations-node/test/test-app/app-server.js
The test `shuts down the NodeSDK when SIGTERM is received` is flaky due to making HTTP requests to `example.com`:
The key improvements are:
1. **Controlled Environment**: Instead of depending on `example.com` (which could be slow/unreachable), we use a local server that responds immediately.
2. **Better Event Handling**: Changed from using `req.on('close')` to `res.on('end')` which is more reliable for confirming the request completed.
3. **Proper Cleanup**: Added `server.close()` to the SIGTERM handler to ensure clean shutdown.
4. **Fixed Timing**: The local server responds immediately, reducing the chance of hitting the test's 1500ms timeout.
The main issue was likely that requests to `example.com` were taking too long or failing, causing the test to hit its timeout before seeing the …
=> fix(auto-instrumentations-node): make SIGTERM shutdown test more reliable

plugins/node/instrumentation-cucumber/.tav.yml, plugins/node/instrumentation-cucumber/src/instrumentation.ts
- Enable support for @cucumber/cucumber@11
=> feat(cucumber): support @cucumber/cucumber@11

examples/connect/docker/collector-config.yaml, examples/connect/docker/docker-compose.yaml, examples/fastify/docker/docker-compose.yaml, examples/graphql/docker/collector-config.yaml, examples/graphql/docker/docker-compose.yaml, examples/mysql/docker/docker-compose.yaml, examples/react-load/preact/docker/docker-compose.yaml, examples/react-load/react/docker/collector-config.yaml, examples/react-load/react/docker/docker-compose.yaml, examples/web/docker/docker-compose.yaml
- This was needed because I was trying to run the graphql example and ran into a problem where the image of the collector was so old that an arm release of the container wasn't available.
- updated all the collectors in various examples to the latest current release of the collector.
- updated the collector config and ran docker compose up to ensure they all worked
=> chore(deps): update collector images in examples

plugins/web/opentelemetry-instrumentation-user-interaction/test/userInteraction.nozone.test.ts, plugins/web/opentelemetry-plugin-react-load/src/BaseOpenTelemetryComponent.ts, plugins/web/opentelemetry-plugin-react-load/test/BaseOpenTelemetryComponent.test.ts
For `@opentelemetry/core@2.0.0` we'll remove `isWrapped()` since it's duplicated in `@opentelemetry/instrumentation`. It makes more sense to have it in `@opentelemetry/instrumentation` since that's actually an instrumentation-related utility function.
Refs https://github.com/open-telemetry/opentelemetry-js/pull/5444
Uses `isWrapped()` from `@opentelemetry/instrumentation` instead. It is a drop-in replacement as the implementations are identical:
- from core: https://github.com/open-telemetry/opentelemetry-js/blob/4553b29d4a04b5b7e4bf87cad64dc2fc8c740d8e/packages/opentelemetry-core/src/utils/wrap.ts#L19-L30
- from instrumentation: https://github.com/open-telemetry/opentelemetry-js/blob/fdab6422ae238b04beb2e92ac38153e35e5800ac/experimental/packages/opentelemetry-instrumentation/src/utils.ts# …
=> refactor: use isWrapped from instrumentation package

detectors/node/opentelemetry-resource-detector-gcp/src/detectors/GcpDetector.ts
We're planning to remove `getEnv()` as it does not scale well when everyone has to update `@opentelemetry/core` to get their env vars. For `OTEL_*` there will be a replacement utility function. For all others, when the package does not need to be browser-compatible (which seems to be the case here) using `process.env` directly should be fine.
Refs https://github.com/open-telemetry/opentelemetry-js/pull/5443
This PR removes `getEnv()` with `process.env` and inlines the defaults from `@opentelemetry/core`'s `DEFAULT_ENVIRONMENT`
=> refactor(resource-detector-gcp): migrate away from getEnv()

package-lock.json, package.json, packages/opentelemetry-test-utils/package.json, plugins/web/opentelemetry-plugin-react-load/package.json
Fixes these 'lint:deps' hits:
```
Unused dependencies (2)
@opentelemetry/otlp-transformer  packages/opentelemetry-test-utils/package.json
@opentelemetry/core              plugins/web/opentelemetry-plugin-react-load/package.json
Unlisted dependencies (1)
@opentelemetry/instrumentation  plugins/web/opentelemetry-plugin-react-load/src/BaseOpenTelemetryComponent.ts
```
`lint:deps` was accidentally removed in a merge-from-main in https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2493.
=> chore: restore lint:deps checking; fix some deps issues

metapackages/auto-instrumentations-node/src/register.ts, metapackages/auto-instrumentations-node/src/utils.ts, metapackages/auto-instrumentations-node/test/utils.test.ts
We're planning to remove `getEnv()` as it does not scale well when everyone has to update `@opentelemetry/core` to get their env vars. For `OTEL_*` there will be a replacement utility function, but until this one is available, we can use `process.env` directly.
Refs https://github.com/open-telemetry/opentelemetry-js/pull/5443
Moves code for parsing `OTEL_LOG_LEVEL` to `@opentelemetry/auto-instrumentations-node` here. It may be changed later as we add similar code to `@opentelemetry/sdk-node`.
=> refactor(auto-instrumentations-node): migrate away from getEnv()

plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts
- https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2747
- This log is not an actual error, because it is really just a warning. Thus, change it to `debug` log.
- It could be argued that this could be `warn` log instead, but given the default `info` log level, these logs appear in each Lambda invocation when TracerProvider and/or MeterProvider are not configured, which is a bit noisy for logs.
=> fix(instrumentation-aws-lambda): Change endSpan error-logs for forceflush into debug-logs

package-lock.json
https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2758 added `test-all-versions` dependency in the `package.json` file of `kafkajs` instrumentation.
However the `package-lock.json` file in root was not updated. So now PRs make a change whenever `npm install` is ran. The 1st problem is that since the change is in root `nx affected` considerd that all packages are affected the unit tests run for all packages instead of only the modified ones.
- checkout main
- run `npm intstall`
- push `package-lock.json`
NOTE: I wonder if it's possible to add a guard in CI for this case.
=> chore(instr-kafkajs): add missing dev-dep

package-lock.json, plugins/node/opentelemetry-instrumentation-nestjs-core/.tav.yml, plugins/node/opentelemetry-instrumentation-nestjs-core/package.json, plugins/node/opentelemetry-instrumentation-nestjs-core/src/instrumentation.ts
- nest-core instrumentation is not supporting last version of NestJS (11)
- Adding support for NestJS 11
=> feat(instrumentation-nestjs-core): add support for NestJS 11

metapackages/auto-instrumentations-node/README.md
The latest version of the auto-instrumentation package is only compatible with 2.x/0.2xx versions. Update the README accordingly.
=> chore: update auto-instrumentations README.md

packages/opentelemetry-host-metrics/src/BaseMetrics.ts
Currently 'new HostMetrics();' will diag.warn 'No meter provider, using default'.
This shouldn't be a warning. It is fine to use the default meter provider.
/cc @legendecas as code owner
=> chore(host-metrics): do not diag.warn if using default options

metapackages/auto-instrumentations-node/package.json, metapackages/auto-instrumentations-node/src/register.ts, metapackages/auto-instrumentations-node/src/utils.ts, metapackages/auto-instrumentations-node/test/utils.test.ts
With https://github.com/open-telemetry/opentelemetry-js/pull/5443 we've introduced new utility functions for getting getting environment variables in an OTel Spec compliant manner, and we've migrated from using the old getEnv() utility function (https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2708).
However, to provide an easier upgrade-path, for users of getEnv() we've also introduced a [utility function to get a log level from a string](https://github.com/open-telemetry/opentelemetry-js/blob/b322a24b4a3296577fb908c0bc9b33efc57c501e/packages/opentelemetry-core/src/utils/configuration.ts#L28-L50), so the mapping we now do is now obsolete and we should align it with the core repo.
Refs https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2774
Removed …
=> refactor(auto-instrumentations-node): use env var utility functions to setup diagnostics logging

nx.json
Fixes `nx.json` configuration for caching. The `input` globs need to have the recursive lookup for typescript files `**/*.ts` otherwise it will compile only once from the root folder even if you do changes in a package later.
The issue impacts only locally and not in the CI.
- modify the glob patter in `nx.json` inputs
=> chore: update `nx.json` for better caching

.github/component-label-map.yml, plugins/node/instrumentation-kafkajs/README.md, plugins/node/instrumentation-kafkajs/src/instrumentation.ts, plugins/node/instrumentation-kafkajs/test/kafkajs.test.ts
The tests broke on kafkajs@1.7.0 and earlier.
The instrumentation crashed on kafkajs@1.4.8 and earlier.
Refs: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2784#issuecomment-2795236903
Fixes: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2784
=> fix(instrumentation-kafkajs): fix instr to work with kafkajs@1.7.0 and earlier

plugins/node/opentelemetry-instrumentation-nestjs-core/README.md
- README is not up-to-date with code
- Updates supported versions in nestjs README
#2685 added support for NestJS 11 and I can confirm the latest released artifact works fine with it, so this updates the README to reflect it. I wasn't sure if it's better to remove `<YY` for `YY` that don't exist yet or keep it to not "pre-support" new major versions, let me know which is better.
=> chore(instrumentation-nestjs): update nestjs supported versions

plugins/node/opentelemetry-instrumentation-aws-sdk/test/bedrock-runtime.test.ts
- https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2806
- manually configure the Bedrock Runtime client to use NodeHttpHandler (instead of the new default NodeHttp2Handler) in tests so Nock will work, similarly to what is done for [Kinesis client test](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/instrumentation-aws-sdk-v0.51.0/plugins/node/opentelemetry-instrumentation-aws-sdk/test/kinesis.test.ts#L55-L59).
Locally changed the `devDependencies` for aws sdk instrumentation to use `"@aws-sdk/client-bedrock-runtime": "3.798.0"`, then ran the tests which succeeded.
=> test(instrumentation-aws-sdk): update client in bedrock-runtime tests to use NodeHttpHandler instead of the new default NodeHttp2Handler

metapackages/auto-instrumentations-node/test/register.test.ts
Fixes: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2814
=> test(auto-instrumentations-node): fix spurious test timeout from variable runtime of cloud resource detectors

examples/connect/tracing.js, examples/graphql/tracer.js, examples/koa/src/tracer.ts, examples/memcached/tracer.js, examples/mysql/src/tracer.ts, examples/react-load/react/src/web-tracer.js, examples/redis/src/tracer.ts, examples/web/examples/document-load/index.js, examples/web/examples/meta/index.js, examples/web/examples/user-interaction/index.js
Refs: #2377
Note: I did *not* work through the steps for each example. Clearly many of these examples are out of date and need work. However, there is no way this change will add *more* breakage, examples/**/package.json include `"@opentelemetry/semantic-conventions": "^1.27.0",` and version 1.27.0 has the `ATTR_SERVICE_NAME` export being used.
=> refactor(examples): update semconv usage to ATTR_ exports

plugins/node/opentelemetry-instrumentation-graphql/test/graphql.test.ts
=> test(instrumentation-graphql): update semconv usage to ATTR_ exports

plugins/node/opentelemetry-instrumentation-koa/src/index.ts
KoaLayerType is an enum. It was erroneously exported as a type causing errors on in Koa setups. This breaks the configuration setup for ignoring certain Koa Layers when publishing spans. 
This was working in @opentelemetry/instrumentation-koa v0.46.0, now broken in v0.50.0.
Typescript linter error:
=> fix: export KoaLayerType enum correctly

packages/instrumentation-runtime-node/src/instrumentation.ts, packages/instrumentation-runtime-node/test/instrumentation.test.ts
This instrumentation overrides the enable() and disable() methods. However,
it was not calling super for those, so the private '_enabled' state on
the super class was not getting updated, which broke 'instr.isEnable()'.
It would always return false.
```js
> var mod = require('@opentelemetry/instrumentation-runtime-node')
undefined
> var instr = new mod.RuntimeNodeInstrumentation()
undefined
> instr.isEnabled()
false
> instr.enable()
undefined
> instr.isEnabled()
false
```
That last `.isEnabled()` result should be `true`.
=> fix(instrumentation-runtime-node): fix .isEnabled()

packages/instrumentation-winston/package.json, packages/instrumentation-winston/test/winston.test.ts, packages/winston-transport/src/utils.ts, packages/winston-transport/test/openTelemetryTransport.test.ts
Before this change the "log sending" feature of instr-winston would
incorrectly include ANSI color codes in the `severityText` for emitted
OTel LogRecords when the winston logger being instrumented was
configured with the `colorize()` formatter, e.g.:
const logger = winston.createLogger({
format: winston.format.combine(
winston.format.timestamp(),
winston.format.colorize(),
winston.format.simple()
),
...
This is because the winston-transport.OpenTelemetryTransportV3 was using
the Winston log info's "level" attribute... which was tweaked by
`colorize()`. Winston log `info` objects have a `Symbol.for("info")`
property which has the unchanged level name:
https://github.com/winstonjs/winston#streams-objectmode-and-info-objects
This commit *also* changes (fix) what `npm test` runs in the …
=> fix(winston-transport, instrumentation-winston): get the correct severityText and severityNumber with winston.format.colorize() is used

package-lock.json, package.json
- Shrink npm install size by removing unused eslint config.
- Removed the Airbnb base eslint config that was added in 2022 but is no longer in use.
=> chore(eslint): remove unused airbnb config

package-lock.json, packages/instrumentation-mongodb/package.json, packages/instrumentation-mongodb/test/mongodb-v5-v6.test.ts
The new release of `mongodb@6.19.0` changed the internal model of, at least, the insert command response. this does not break the instrumentation but the `responseHook` tests were relying on that to make certain assertions. As a result running `test-all-versions` failed when selecting such version of the package.
- update dependency to v6.19.0
- change test code to consider both models in the response object
=> test(instr-mongodb): fix tests mongdb tests for 6.19.0

package-lock.json, package.json, scripts/package.json
No problem, just cleaning up.
Updated the name of the root package to reflect the repo.
- `opentelemetry-contrib` --> `opentelemetry-js-contrib`
- same thing in ./scripts
- Removed non-existent exports at root
=> chore(package): rename repo and scripts packages

packages/resource-detector-gcp/test/detectors/GcpDetectorIntegration.test.ts, packages/resource-detector-gcp/test/detectors/fixtures/detect-with-http-instrumentation.mjs
Isolate `GcpDetectorIntegration.test.ts` (using `runTestFixture()`) so that it doesn't leak it's changes into other test cases
This was breaking some tests I am working on for https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2933#issuecomment-3235170977. It also just overall simplifies the test since we don't need to play with `require.cache`.
I verified this test fails properly without `suppressTracing()` in the detector.
=> test(gcp-detector): properly isolate GcpDetectorIntegration.test.ts

packages/instrumentation-pg/test/pg-pool.test.ts, packages/instrumentation-pg/test/pg.test.ts
- Locally I was unable to pass `npm run test` if the db service was not started.
- I copied the guard from the regular test to the ESM version. I have no prior experience with the db packages so please close this if it's off base.
=> chore(instrumentation-pg): skip test if db not running

.github/workflows/release-please.yml
Similar to https://github.com/open-telemetry/opentelemetry-js/pull/5946
Nothing has happened to us, but with everything that's been happening recently, this PR does a few things to harden our publishing process:
- switches publishing from token-based to OIDC
- I have already updated all packages to disallow token publish, and set up OIDC for all of the packages published from this repo
- makes use of a new `npm-publish-environment` environment, to lock down who can actually publish to npm
until recently access was more broad, but additonal maintainer approval will now be required for publishing here and in contrib
- requiring the environment and OIDC will also limit a potential blast radius to one repo, we can set up to require multiple more than one maintainer approval before publishing. …
=> ci: harden publish workflow by switching to OIDC

.github/workflows/release-please.yml
- The release-please PR can include *multiple* commits, so we need to amend
the author on all of them to pass EasyCLA.
- The logic for guarding on releases_created was wrong: I believe because
it is a *string* true or false, rather than a boolean that works the
way it was previously.
Refs: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/3099
=> ci(release-please): pass EasyCLA, correct if-logic for releases_created var

.github/workflows/release-please.yml
Alternative to #3104 
Refs #3099 
`otelbot-js-contrib` now has the CLA signed, we can merge this and avoid re-writing commits all together.
=> ci(release-please): avoid re-writing commits on release PR

packages/instrumentation-bunyan/README.md
We're still having problems with the new release workflow. ODIC support was added in `lerna@9`, so the run likely failed for that reason. 
This PR is intended for another round of testing the release-please workflow, after updating to `lerna@9` #3114. It triggers a new release PR for `@opentelemetry/instrumentation-bunyan`, by making a minimal `README.md` change. 
Refs:
- tracking issue #3099
- https://github.com/open-telemetry/opentelemetry-js-contrib/actions/runs/18020717167/job/51277286471 -failed workflow run
- #3111 - to force a PR for all packages when we know the workflow works.
=> fix: force new release PR

packages/instrumentation-undici/src/undici.ts
Refs: https://github.com/open-telemetry/opentelemetry-js/issues/5956
=> chore(instrumentation-undici): update metric names to semconv `METRIC_*` exports

packages/instrumentation-aws-sdk/src/semconv.ts, packages/instrumentation-aws-sdk/src/services/bedrock-runtime.ts
I missed one in #3126.
Refs: https://github.com/open-telemetry/opentelemetry-js/issues/5956
=> chore(instrumentation-aws-sdk): update metric names to semconv `METRIC_*` exports (take 2)

.github/workflows/release-please.yml
Now that we are on npm lockfileVersion=3, which doesn't have the 'dependencies'
legacy key, we *should* no longer need this sync.
Note that for the recent release-please PR there *was* some churn in 'peer'
entries in the package-lock file from this step:
https://github.com/open-telemetry/opentelemetry-js-contrib/pull/3135/commits/54c1f5beafcc91e4cab497edfea738e3b25599b9
My educated guess is that this is *not* impactful, not necessary for
the release-please workflow.
=> chore(release-please): drop unneeded package-lock sync as part of the release PR

packages/instrumentation-pino/.tav.yml, packages/instrumentation-pino/src/instrumentation.ts
Pino 10 was released recently. Node.js 18 support was dropped.
Fixes: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/3143
=> feat(instrumentation-pino): support pino@10

packages/instrumentation-mysql2/.tav.yml
Reduces the number of versions tested when running `test-all-versions` - with newer major versions being tested more thoroughly than older ones.
**Currently we test:**
```
-- 24 package versions matching filter: 1.4.2, 1.5.3, 1.6.6, 1.7.0, 2.0.2, 2.1.0, 2.2.5, 2.3.2, 3.0.1, 3.1.2, 3.2.4, 3.3.5, 3.4.5, 3.5.2, 3.6.5, 3.7.1, 3.8.0, 3.9.9, 3.10.3, 3.11.5, 3.12.0, 3.13.0, 3.14.5, 3.15.1
```
**With this PR we test:**
```
-- 7 package versions matching filter: 3.0.0, 3.3.1, 3.5.1, 3.9.2, 3.11.0, 3.14.5, 3.15.1
-- 3 package versions matching filter: 1.4.2, 2.3.0, 2.3.2
```
=> test(mysql2): reduce number of versions tested

packages/instrumentation-typeorm/.tav.yml
Reduces the number of versions tested when running test-all-versions.
**Currently we test:**
```
-- 28 package versions matching filter: 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.13, 0.3.14, 0.3.15, 0.3.16, 0.3.17, 0.3.18, 0.3.19, 0.3.20, 0.3.21, 0.3.22, 0.3.23, 0.3.24, 0.3.25, 0.3.26, 0.3.27
```
**With this PR we test:**
```
-- 7 package versions matching filter: 0.3.0, 0.3.4, 0.3.9, 0.3.14, 0.3.19, 0.3.25, 0.3.27
```
=> test(typeorm): reduce number of versions tested

packages/instrumentation-express/README.md
Refs: #2801
---
h/t this comment on a closed issue: https://github.com/open-telemetry/opentelemetry-js-contrib/pull/2801#issuecomment-3181224090
=> docs(instrumentation-express): update README to note that express@5 is supported
